<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PostsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('posts')->delete();
        
        \DB::table('posts')->insert(array (
            0 => 
            array (
                'id' => 1,
                'category_id' => 1,
                'user_id' => 1,
                'cover' => NULL,
                'title' => 'Visi dan Misi',
                'slug' => 'visi-dan-misi',
            'desc' => '<h4><strong>VISI</strong></h4><p>Kementerian Agama yang profesional dan andal dalam membangun masyarakat yang saleh, moderat, cerdas dan unggul untuk mewujudkan Indonesia maju yang berdaulat, mandiri dan berkepribadian berdasarkan gotong royong</p><p>&nbsp;</p><h4><strong>MISI</strong></h4><p><strong>1. PROFESIONAL,</strong>&nbsp;Memiliki keahlian dan keterampilan yang memerlukan kepandaian khusus;</p><p><strong>2. ANDAL,</strong>&nbsp;Bahwa dapat dipercaya dalam menghasilkan produk yang berkualitas;</p><p><strong>3. SALEH,</strong>&nbsp;Taat dan sungguh-sungguh menjalankan ibadah;</p><p><strong>4. MODERAT,</strong>&nbsp;Selalu menghindarkan perilaku atau pengungkapan yang ekstrem dan berkecenderungan ke arah dimensi atau jalan tengah;</p><p><strong>5. CERDAS,</strong>&nbsp;Sempurna perkembangan akal budinya (untuk berpikir, mengerti, dan sebagainya) dan tajam pikiran;</p><p><strong>6. UNGGUL,</strong>&nbsp;Lebih tinggi (pandai, baik, cakap, kuat, awet, dan sebagainya) daripada yang lain-lain;</p>',
                'keywords' => 'Visi Misi',
                'meta_desc' => 'Visi Misi',
                'is_news' => 'no',
                'reads' => 41,
                'created_at' => '2023-08-30 08:37:43',
                'updated_at' => '2023-08-31 05:32:59',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'category_id' => 1,
                'user_id' => 1,
                'cover' => NULL,
                'title' => 'Struktur Organisasi',
                'slug' => 'struktur-organisasi',
                'desc' => '<p>Struktur Organisasi Kementerian Agama Kabupaten Pesisir Selatan</p><figure class="image"><img src="http://ppid.kemenagpessel.com/media/Struktur Organisasi_1693371401.png"></figure>',
                'keywords' => 'Struktur Organisasi',
                'meta_desc' => 'Struktur Organisasi',
                'is_news' => 'no',
                'reads' => 25,
                'created_at' => '2023-08-30 08:50:34',
                'updated_at' => '2023-08-31 00:00:29',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'category_id' => 4,
                'user_id' => 1,
                'cover' => NULL,
                'title' => 'Prosedur Permohonan Informasi',
                'slug' => 'prosedur-permohonan-informasi',
                'desc' => '<p>Prosedur Permohonan Informasi<br>&nbsp;</p><figure class="image"><img src="http://ppid.kemenagpessel.com/media/tc_permohonan_1693484397.jpg"></figure>',
                'keywords' => 'Prosedur Permohonan Informasi',
                'meta_desc' => 'Prosedur Permohonan Informasi',
                'is_news' => 'no',
                'reads' => 19,
                'created_at' => '2023-08-30 09:23:51',
                'updated_at' => '2023-08-31 19:26:56',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'category_id' => 4,
                'user_id' => 1,
                'cover' => NULL,
                'title' => 'Prosedur Pengajuan Keberatan',
                'slug' => 'prosedur-pengajuan-keberatan',
                'desc' => '<p>Prosedur Pengajuan Keberatan</p><figure class="image"><img src="http://ppid.kemenagpessel.com/media/tc_pengajuan_1693484448.jpg"></figure>',
                'keywords' => 'Prosedur Pengajuan Keberatan',
                'meta_desc' => 'Prosedur Pengajuan Keberatan',
                'is_news' => 'no',
                'reads' => 28,
                'created_at' => '2023-08-30 09:24:18',
                'updated_at' => '2023-08-31 19:20:57',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'category_id' => 4,
                'user_id' => 1,
                'cover' => NULL,
                'title' => 'Prosedur Sengketa Informasi',
                'slug' => 'prosedur-sengketa-informasi',
                'desc' => '<p>Prosedur Sengketa Informasi</p><figure class="image"><img src="http://ppid.kemenagpessel.com/media/tc_sengketa_1693484509.jpg"></figure>',
                'keywords' => 'Prosedur Sengketa Informasi',
                'meta_desc' => 'Prosedur Sengketa Informasi',
                'is_news' => 'no',
                'reads' => 18,
                'created_at' => '2023-08-30 09:24:35',
                'updated_at' => '2023-09-01 10:27:31',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'category_id' => 5,
                'user_id' => 1,
                'cover' => NULL,
                'title' => 'Maklumat Pelayanan',
                'slug' => 'maklumat-pelayanan',
                'desc' => '<p>Maklumat Pelayanan</p>',
                'keywords' => 'Maklumat Pelayanan',
                'meta_desc' => 'Maklumat Pelayanan',
                'is_news' => 'no',
                'reads' => 12,
                'created_at' => '2023-08-30 10:51:04',
                'updated_at' => '2023-09-01 10:27:05',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'category_id' => 5,
                'user_id' => 1,
                'cover' => NULL,
                'title' => 'Jadwal Pelayanan',
                'slug' => 'jadwal-pelayanan',
                'desc' => '<p>Jadwal Pelayanan</p><p>Layanan permohonan informasi pada PPID Kementerian Agama dilaksanakan pada hari kerja, mulai Senin s.d Jumat, dengan ketentuan waktu sebagai berikut.</p><ol><li>Senin s.d Kamis:<ul><li>Jam Layanan : 09.00 WIB - 15.00 WIB</li><li>Istirahat, Shalat, Makan : 12.00 WIB - 13.00 WIB</li></ul></li><li>Jum\'at<ul><li>Jam Layanan : 09.00 WIB - 15.00 WIB</li><li>Istirahat, Shalat, Makan : 11.00 WIB - 13.00 WIB</li></ul></li></ol><p>&nbsp;</p>',
                'keywords' => 'Jadwal Pelayanan',
                'meta_desc' => 'Jadwal Pelayanan',
                'is_news' => 'no',
                'reads' => 14,
                'created_at' => '2023-08-30 10:51:19',
                'updated_at' => '2023-09-01 10:27:10',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'category_id' => 5,
                'user_id' => 1,
                'cover' => NULL,
                'title' => 'Biaya Tarif Layanan',
                'slug' => 'biaya-tarif-layanan',
            'desc' => '<p><strong>Biaya Tarif Layanan</strong></p><p>PPID Kementerian Agama menyediakan informasi publik secara <strong>gratis (tidak dipungut biaya)</strong>. Adapun untuk penggandaan atau perekaman, pemohon/ pengguna informasi publik dapat melakukan penggandaan/ fotocopy sendiri di sekitar gedung Kementerian Agama atau menyediakan CD/DVD kosong atau flashdisk untuk perekaman data dan informasinya.</p>',
                'keywords' => 'Biaya Tarif Layanan',
                'meta_desc' => 'Biaya Tarif Layanan',
                'is_news' => 'no',
                'reads' => 8,
                'created_at' => '2023-08-30 10:51:40',
                'updated_at' => '2023-09-01 10:27:22',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'category_id' => 1,
                'user_id' => 1,
                'cover' => NULL,
                'title' => 'Standar Pelayanan',
                'slug' => 'standar-pelayanan',
                'desc' => '<p>Standar Pelayanan</p>',
                'keywords' => 'Standar Pelayanan',
                'meta_desc' => 'Standar Pelayanan',
                'is_news' => 'no',
                'reads' => 8,
                'created_at' => '2023-08-30 10:52:02',
                'updated_at' => '2023-09-01 10:27:18',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'category_id' => 1,
                'user_id' => 1,
                'cover' => NULL,
                'title' => 'Profil PPID',
                'slug' => 'profil-ppid',
            'desc' => '<p>Dalam rangka memberikan pelayanan Informasi Publik sebagaimana diamanatkan dalam Peraturan Pemerintah Nomor 61 Tahun 2010 tentang Pelaksanaan Undang-Undang Nomor 14 Tahun 2008 tentang Keterbukaan Informasi Publik, Menteri Agama menetapkan Pejabat Pengelola informasi dan Dokumentasi (PPID) melalui Keputusan Menteri Agama (KMA) Nomor 200 Tahun 2012 tentang Pejabat Pengelola Informasi dan Dokumentasi (PPID) Kementerian Agama dan diperbaharui menjadi Keputusan Menteri Agama (KMA) Nomor 533 Tahun 2018 tentang Pejabat Pengelola Informasi dan Dokumentasi Kementerian Agama dan Atasan Pejabat Pengelola Informasi dan Dokumentasi Kementerian Agama dan diperbaharui menjadi Keputusan Menteri Agama (KMA) Nomor 461 Tahun 2020 tentang Pejabat Pengelola Informasi dan Dokumentasi Kementerian Agama, dan Atasan Pejabat Pengelola Informasi dan Dokumentasi Kementerian Agama dan diperbaharui lagi menjadi Keputusan Menteri Agama (KMA) Nomor 657 Tahun 2021 tentang Pejabat Pengelola Informasi dan Dokumentasi Kementerian Agama, dan Atasan Pejabat Pengelola Informasi dan Dokumentasi Kementerian Agama. Pada Keputusan Menteri Agama Nomor 657 Tahun 2021 tersebut ditetapkan bahwa PPID Kementerian Agama dan Atasan PPID Kementerian Agama terdiri atas:<br><br>I. Pejabat Pengelola Informasi dan Dokumentasi (PPID) Kementerian Agama:<br> 1. PPID Utama yaitu Biro Humas, Data, dan Informasi Sekretariat Jenderal;<br> 2. PPID Unit yaitu:<br>   a) PPID Unit Eselon I Pusat yaitu Kepala Biro Humas, Data, dan Informasi sebagai PPID Unit Sekretariat Jenderal, Sekretaris Unit Eselon I pada Satuan Kerja Inspektorat Jenderal, Direktorat Jenderal Pendidikan Islam, Direktorat Jenderal Bimbingan Masyarakat Islam, Direktorat Jenderal Bimbingan Masyarakat Kristen, Direktorat Jenderal Bimbingan Masyarakat Katolik, Direktorat Jenderal Bimbingan Masyarakat Hindu, Direktorat Jenderal Bimbingan Masyarakat Buddha, Badan Penelitian dan Pengembangan serta Diklat, Badan Penyelenggara Jaminan Produk Halal;<br>   b) PPID Unit Kantor Wilayah Kementerian Agama Provinsi yaitu Kepala Bagian Tata Usaha (34 Unit);<br>   c) PPID Unit Kantor Kementerian Agama Kabupaten/Kota yaitu Kepala Subbagian Tata Usaha (512 Unit);<br>   d) PPID Unit Universitas/Institut dijabat oleh Wakil Rektor II, sedangkan PPID Unit Sekolah Tinggi dijabat oleh Wakil Ketua II. PPID Unit Perguruan Tinggi Keagamaan Negeri (PTKN) terdiri dari: Universitas Islam Negeri (23 Unit), Institut Agama Islam Negeri (29 Unit), Sekolah Tinggi Agama Islam Negeri (5 Unit), Institut Agama Kristen Negeri (6 Unit), Sekolah Tinggi Agama Kristen Protestan Negeri (1 Unit), Sekolah Tinggi Agama Katolik Negeri (1Unit), Universitas Hindu Negeri (1 Unit), Institut Agama Hindu Negeri (2 Unit), Sekolah Tinggi Agama Hindu Negeri (1 Unit), Sekolah Tinggi Agama Buddha Negeri (2 Unit).<br>   e) PPID Unit Balai yaitu Kepala Subbagian Tata Usaha. PPID Unit Balai terdiri dari: PPID Balai Penelitian dan Pengembangan Agama (3 Unit), dan PPID Balai Pendidikan dan Pelatihan Keagamaan (14 Unit).<br><br>II. Atasan Pejabat Pengelola Informasi dan Dokumentasi (PPID) Kementerian Agama:<br> 1. Atasan PPID Kementerian Agama yaitu Sekretaris Jenderal;<br> 2. Atasan PPID Unit yaitu:<br>   a) Atasan PPID Unit Eselon I Pusat yaitu Sekretaris Jenderal, Inspektur Jenderal, Direktur Jenderal Pendidikan Islam, Direktur Jenderal Bimbingan Masyarakat Islam, Direktur Jenderal Bimbingan Masyarakat Kristen, Direktur Jenderal Bimbingan Masyarakat Katolik, Direktur Jenderal Bimbingan Masyarakat Hindu, Direktur Jenderal Bimbingan Masyarakat Buddha, Kepala Badan Penelitian dan Pengembangan serta Diklat, Kepala Badan Penyelenggara Jaminan Produk Halal;<br>   b) Atasan PPID Unit Kantor Wilayah Kementerian Agama Provinsi yaitu Kepala Kantor Kementerian Agama Wilayah Provinsi (34);<br>   c) Atasan PPID Unit Kantor Kementerian Agama Kabupaten/Kota yaitu Kepala Kantor Kementerian Agama Kabupaten/Kota (512);<br>   d) Atasan PPID Unit Universitas/Institut yaitu Rektor, sedangkan Atasan PPID Unit Sekolah Tinggi yaitu Ketua.<br>   e) Atasan PPID Unit Balai yaitu Kepala Balai.<br><br>Agar pelaksanaan keterbukaan informasi publik pada satuan kerja Pusat dan Daerah berjalan dengan baik, Menteri Agama menetapkan Keputusan Menteri Agama Nomor 92 Tahun 2019 tentang Pedoman Layanan Informasi Publik Bagi Pejabat Pengelola Informasi dan Dokumentasi Kementerian Agama dan Atasan Pejabat Pengelola Informasi dan Dokumentasi Kementerian Agama.<br><br>PPID Utama maupun PPID Unit Kementerian Agama bertanggung jawab untuk melakukan penyediaan, penyimpanan, pendokumentasian, pelayanan, dan pengamanan informasi publik.</p>',
                'keywords' => 'Profil PPID',
                'meta_desc' => 'Profil PPID',
                'is_news' => 'no',
                'reads' => 27,
                'created_at' => '2023-08-30 12:57:30',
                'updated_at' => '2023-08-31 15:19:06',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'category_id' => 1,
                'user_id' => 1,
                'cover' => NULL,
                'title' => 'Profil Pejabat',
                'slug' => 'profil-pejabat',
            'desc' => '<p>PPID Kementerian Agama dibentuk berdasarkan Keputusan Menteri Agama (KMA) Nomor 657 Tahun 2021 tentang Pejabat Pengelola Informasi dan Dokumentasi Kementerian Agama dan Atasan Pejabat Pengelola Informasi dan Dokumentasi Kementerian Agama, sebagai berikut.</p><h4><strong>PPID Kementerian Agama Kab. Pesisir Selatan</strong></h4><figure class="table"><table><tbody><tr><td>Atasan PPID :</td><td>Kepala Kantor Kementerian Agama Kab. Pesisir Selatan</td></tr><tr><td>PPID :</td><td>Kepala Sub Bagian Tata Usaha Kementerian Agama Kab. Pesisir Selatan</td></tr><tr><td>Alamat :</td><td>Jln. Imam Bonjol, Kec. IV Jurai, Painan, Kab. Pesisir Selatan</td></tr><tr><td>Telepon :</td><td>(0756) 21305 – 21405</td></tr><tr><td>Email :</td><td>pessel@kemenag.go.id</td></tr><tr><td>Website :</td><td>ppid.kemenagpessel.com</td></tr></tbody></table></figure>',
                'keywords' => 'Profil Pejabat',
                'meta_desc' => 'Profil Pejabat',
                'is_news' => 'no',
                'reads' => 8,
                'created_at' => '2023-08-30 12:57:44',
                'updated_at' => '2023-08-31 00:04:56',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'category_id' => 1,
                'user_id' => 1,
                'cover' => NULL,
                'title' => 'Struktur Organisasi PPID',
                'slug' => 'struktur-organisasi-ppid',
                'desc' => '<p>Struktur Organisasi PPID</p><figure class="image"><img src="http://ppid.kemenagpessel.com/media/STRUKTUR PPID_1693531684.png"></figure>',
                'keywords' => 'Struktur Organisasi PPID',
                'meta_desc' => 'Struktur Organisasi PPID',
                'is_news' => 'no',
                'reads' => 4,
                'created_at' => '2023-08-30 12:59:43',
                'updated_at' => '2023-09-01 08:28:09',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'category_id' => 1,
                'user_id' => 1,
                'cover' => NULL,
                'title' => 'Tugas dan Fungsi PPID',
                'slug' => 'tugas-dan-fungsi-ppid',
            'desc' => '<p>Tugas, fungsi, &amp; wewenang PPID Kementerian Agama, diantaranya:</p><figure class="table"><table><tbody><tr><td><h4>&nbsp;</h4><h4>Tugas</h4></td></tr><tr><td><p>&nbsp;</p><ol><li>menyediakan dan mengamankan Informasi Publik</li><li>memberikan pelayanan Informasi Publik yang cepat, tepat, dan sederhana;</li><li>menyusun standar operasional prosedur pelaksanaan tugas dan kewenangan PPID Kementerian Agama dalam rangka penyebarluasan Informasi Publik;</li><li>menetapkan Daftar Informasi Publik dalam bentuk keputusan PPID Kementerian Agama mengenai Daftar Informasi Publik Kementerian Agama, paling lambat akhir bulan Januari tahun berjalan;</li><li>melaksanakan Pengklasifikasian Informasi Publik atau perubahannya dengan persetujuan Atasan PPID Kementerian Agama dalam bentuk keputusan PPID Kementerian Agama mengenai klasifikasi informasi Kementerian Agama;</li><li>menetapkan Informasi Publik yang Dikecualikan sebagai Informasi Publik yang dapat diakses dalam hal:<ul><li>telah dinyatakan terbuka bagi masyarakat berdasarkan mekanisme keberatan;</li><li>telah dinyatakan terbuka bagi masyarakat berdasarkan putusan sidang ajudikasi, putusan pengadilan, serta putusan Mahkamah Agung;</li><li>telah habis jangka waktu pengecualiannya; dan/atau</li><li>ditentukan oleh peraturan perundang-undangan;</li></ul></li><li>menetapkan pertimbangan tertulis atas setiap kebijakan yang diambil guna memenuhi hak setiap orang atas Informasi Publik</li><li>mengkoordinasikan<ul><li>pengumpulan seluruh Informasi Publik yang meliputi: informasi yang wajib disediakan dan diumumkan secara berkala, informasi yang wajib diumumkan secara serta merta; dan informasi yang wajib tersedia setiap saat;</li><li>pengumpulan Informasi Publik yang Dikecualikan;</li><li>pengumuman Informasi Publik melalui media yang secara efektif dan efisien dapat menjangkau seluruh pemangku kepentingan;</li><li>penyampaian Informasi Publik dalam bahasa Indonesia yang baik, benar, dan mudah dipahami;</li><li>pemenuhan permohonan Informasi Publik yang dapat diakses oleh publik;</li><li>pengklasifikasian Informasi Publik dan/ atau pengubahan Pengklasifikasian Informasi Publik;</li><li>permohonan keberatan di proses berdasarkan prosedur;</li><li>proses layanan Informasi Publik di Kementerian Agama berjalan dengan baik;</li></ul></li><li>melakukan Uji Konsekuensi bersama dengan PPID Unit eselon I terhadap Informasi Publik yang tidak dapat diakses oleh masyarakat sebagaimana dimaksud dalam peraturan perundang-undangan mengenai keterbukaan Informasi Publik;</li><li>memberikan alasan tertulis atas pengecualian Informasi Publik, dalam hal permohonan Informasi Publik ditolak;</li><li>melakukan penghitaman atau pengaburan materi Informasi Publik yang Dikecualikan beserta alasannya;</li><li>menetapkan dan menugaskan petugas layanan informasi untuk membantu pelaksanaan tugas PPID Kementerian Agama;</li><li>melakukan pengembangan kompetensi petugas layanan informasi guna meningkatkan kualitas layanan informasi publik;</li><li>menggunakan Sistem Informasi PPID dalam pengelolaan layanan Informasi Publik;</li><li>menyediakan Informasi Publik yang mutakhir pada portal Kementerian Agama dan Sistem Informasi PPID;</li><li>memelihara dan/atau memutakhirkan informasi pada portal Kementerian Agama dan Sistem Informasi PPID sekurang-kurangnya 1 (satu) kali dalam 1 (satu) bulan;</li><li>melakukan koordinasi, harmonisasi, dan fasilitasi Perangkat PPID;</li><li>menyediakan ruangan dan/atau meja layanan Informasi Publik;</li><li>membuat dan menyampaikan Laporan Empat Bulanan Layanan Informasi Publik kepada Atasan PPID Kementerian Agama; dan</li><li>membuat dan mengumumkan Laporan Tahunan layanan Informasi Publik serta menyampaikan salinannya kepada Komisi Informasi Pusat</li></ol><p>&nbsp;</p></td></tr></tbody></table></figure><figure class="table"><table><tbody><tr><td><h4>&nbsp;</h4><h4>Fungsi</h4></td></tr><tr><td>Pembinaan dan pengelolaan Pejabat Pengelola Informasi dan Dokumentasi di lingkungan Kementerian Agama Pusat dan Daerah</td></tr></tbody></table></figure><figure class="table"><table><tbody><tr><td><h4>&nbsp;</h4><h4>Wewenang</h4></td></tr><tr><td><p>&nbsp;</p><ol><li>menetapkan Panitia Pengelola dan Pelayanan Informasi PPID Kementerian Agama;</li><li>memutuskan suatu informasi dapat diakses atau tidak dapat diakses oleh masyarakat berdasarkan Uji Konsekuensi bersama dengan PPID Unit eselon I Pusat;</li><li>menolak permohonan Informasi Publik secara tertulis apabila Informasi Publik yang dimohonkan termasuk Informasi Publik yang Dikecualikan dengan disertai alasan serta pemberitahuan tentang hak dan tata cara bagi Pemohon untuk mengajukan keberatan atas penolakan tersebut;</li><li>menghadiri rapat pembahasan terkait PPID di tingkat kementerian/lembaga;</li><li>meminta informasi kepada PPID Unit pemilik informasi dalam hal Informasi Publik yang dimohonkan oleh Pemohon tidak dikuasai oleh PPID Kementerian Agama namun dikuasai oleh PPID Unit;</li><li>melakukan koordinasi dengan PPID Unit terkait dalam menyelesaikan keberatan;</li><li>melakukan pendampingan dan koordinasi dengan PPID Unit, unit teknis, dan/ atau unit yang memiliki tugas dan fungsi memberikan bantuan hukum, pendapat hukum, dan pertimbangan hukum yang berkaitan dengan tugas Kementerian Agama;</li><li>mengusulkan kepada Atasan PPID Kementerian Agama untuk melaporkan dan/ atau mengajukan gugatan atas putusan Komisi Informasi ke lembaga peradilan;</li><li>melakukan koordinasi dengan PPID Unit eselon I Pusat dalam penyediaan Informasi Publik yang mutakhir pada portal Kementerian Agama dan situs selain portal Kementerian Agama, dan/atau Sistem Informasi PPID;</li><li>melaporkan ketidaksesuaian proses sidang Sengketa Informasi Publik ke Sekretariat Komisi Informasi atas persetujuan Atasan PPID Kementerian Agama; dan</li><li>melakukan sosialisasi untuk meningkatkan pemahaman atas implementasi keterbukaan Informasi Publik di Kementerian Agama.</li><li>melakukan pembinaan PPID Unit Kementerian Agama Pusat dan Daerah.</li><li>melakukan monitoring terhadap pelaksanaan PPID Unit Kementerian Agama Pusat dan Daerah.</li></ol></td></tr></tbody></table></figure>',
                'keywords' => 'Tugas dan Fungsi PPID',
                'meta_desc' => 'Tugas dan Fungsi PPID',
                'is_news' => 'no',
                'reads' => 9,
                'created_at' => '2023-08-30 13:00:11',
                'updated_at' => '2023-08-31 15:19:10',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'category_id' => 1,
                'user_id' => 1,
                'cover' => NULL,
                'title' => 'Visi, Misi dan Moto PPID',
                'slug' => 'visi-misi-dan-moto-ppid',
                'desc' => '<h4><strong>Visi</strong></h4><p>Terwujudnya Pelayanan Informasi yang Akuntabel</p><p><br>&nbsp;</p><h4><strong>Misi</strong></h4><p>1. Meningkatkan layanan informasi yang cepat, tepat, dan transparan<br>2. Meningkatkan kompetensi SDM pelayan informasi<br>3. Penguatan koordinasi antar PPID lintas sektoral</p><p><br>&nbsp;</p><h4><strong>Moto</strong></h4><p>Melayani dengan Ikhlas</p>',
                'keywords' => 'Visi, Misi dan Moto PPID',
                'meta_desc' => 'Visi, Misi dan Moto PPID',
                'is_news' => 'no',
                'reads' => 14,
                'created_at' => '2023-08-30 13:01:45',
                'updated_at' => '2023-08-31 00:05:03',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'category_id' => 6,
                'user_id' => 1,
                'cover' => 'https://res.cloudinary.com/dezj1x6xp/image/upload/v1693412051/PandanViewMandeh/image_750x_64e8b41b3143d_l7yatk.jpg',
                'title' => 'Anggota Komisi VIII DPR RI, Delmeria Apresiasi Kemenag Pessel Sebagai UPP Pelopor Pelayanan Ramah Kelompok Rentan',
                'slug' => 'anggota-komisi-viii-dpr-ri-delmeria-apresiasi-kemenag-pessel-sebagai-upp-pelopor-pelayanan-ramah-kelompok-rentan',
            'desc' => '<p>Usai melakukan kegiatan Ngobrol Pendidikan Islam, Delmeria anggota Komisi VIII DPR RI kunjungi Kantor Kementerian Agama Kabupaten Pesisir Selatan sebagai Unit Pelayanan Publik (UPP) Pelopor Pelayanan Ramah Kelompok Rentan, Jumat (25/8/2023).</p><p>Sebagaimana diketahui, Komisi VIII DPR RI merupakan mitranya kementerian agama yang lingkup tugasnya yaitu mengurus bidang agama, sosial, pemberdayaan perempuan dan perlindungan anak.</p><p>Kepala Kantor Kementerian Agama Kabupaten Pesisir Selatan, Abrar Munanda mengatakan, berdasarkan Undang-undang nomor 25 tahun 2009 tentang Pelayanan Publik, yang dimaksud kelompok rentan antara lain penyandang cacat, lanjut usia, wanita hamil, anak-anak.&nbsp;</p><p>"Dalam menyelenggarakan pelayanan Publik, sebuah lembaga pemerintah harus memberikan pelayanan khusus atau keberpihakan terhadap kelompok rentan," ungkap Abrar Munanda.</p><p>Lebih lanjut dikatakan, guna mendukung pelayanan khusus tersebut, Kantor Kementerian Agama Kabupaten Pesisir Selatan terus berupaya memperbaiki serta melengkapi sarana prasarana yang mendukung pelayanan ramah kelompok rentan.</p><p>"Saat ini Kantor Kementerian Agama Kabupaten Kabupaten Pesisir Selatan merupakan salah satu dari lima satuan kerja yang berada di bawah Kementerian Agama RI yang ditunjuk oleh menteri agama mewakili kementerian agama dalam pelayanan kepada masyarakat terkhusus sebagai UPP pelopor pelayanan ramah kelompok rentan," ujar Abrar.</p><p>Selain itu Delmeria bersama Kakanwil Kementerian Agama Provinsi Sumatera Barat, Helmi juga mengunjungi proyek pembangunan ruangan kegiatan belajar dari dana SBSN yang berlokasi di Man 2 Pesisir Selatan.&nbsp;</p><p>Selanjutnya anggota Komisi VIII DPR RI tersebut bersama kakanwil dan didampingi kakan kemenag dan tim juga mengunjungi rumah tidak layak huni yang menjadi objek kegiatan Benah Rumah Bina Penghuni (Berani).&nbsp;</p><p>Program Berani merupakan salah satu inovasi andalan dari Kantor Kementerian Agama Kabupaten Pesisir Selatan yang tahun ini dilaksanakan pada 10 titik lokasi yang tersebar di Pesisir Selatan.</p><p>Delmeria memberikan apresiasi yang luar biasa terhadap inovasi-inovasi yang telah dilakukan oleh Kantor Kementerian Agama Kabupaten Pesisir Selatan, sekaligus meresmikan salah satu rumah warga yang masuk dalam program berani dengan melakukan pengguntingan pita.</p><p>Pada kesempatan itu Delmeria juga berkenan memberikan bantuan sebesar lima juta rupiah untuk ikut menunjang program Berani tersebut. <strong>(zn)</strong></p><p><br>&nbsp;</p>',
                'keywords' => 'Komisi VIII DPR RI, Kunjungan Kerja',
                'meta_desc' => 'Anggota Komisi VIII DPR RI, Delmeria Apresiasi Kemenag Pessel Sebagai UPP Pelopor Pelayanan Ramah Kelompok Rentan',
                'is_news' => 'yes',
                'reads' => 0,
                'created_at' => '2023-08-30 23:15:22',
                'updated_at' => '2023-08-30 23:25:28',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'category_id' => 6,
                'user_id' => 1,
                'cover' => 'https://res.cloudinary.com/dezj1x6xp/image/upload/v1693412219/PandanViewMandeh/image_750x_64dddb4cc7b28_au8ttd.jpg',
                'title' => 'Kakan Kemenag Pessel Serahkan Penghargaan Dari Menag Kepada Bupati',
                'slug' => 'kakan-kemenag-pessel-serahkan-penghargaan-dari-menag-kepada-bupati',
            'desc' => '<p>Bupati Pesisir Selatan Rusma Yul Anwar menerima penghargaan dari Menteri Agama Republik Indonesia Yaqut Cholil Choumas.</p><p>Penghargaan diberikan kepada Bupati atas partisipasi dan kontribusi dalam pengembangan dan kebijakan positif dalam mendukung program Penguatan Fungsi Penyuluh Agama dan Pembentukan Kampung Moderasi Beragama dari Menteri Agama (Menag) RI.</p><p>Penghargaan tersebut diserahkan melalui Kepala Kantor Kementerian Agama Kabupaten Pesisir Selatan, Abrar Munanda, usai upacara bendera peringatan HUT ke-78 RI Tahun 2023 di GOR Ilyas Yacub Painan, Kamis (17/8/2023).</p><p>Hadir dalam kesempatan itu Wakil Bupati, Rudi Hariyansyah, pimpinan DPRD, Aprial Habas, Forkopimda dan disaksikan segenap hadirin peserta upacara peringatan HUT ke-78 RI di lingkup Pemerintah Kabupaten Pesisir Selatan.</p><p>Atas nama Kepala Daerah Rusma Yul Anwar, menyampaikan ucapan terima kasih atas penghargaan tersebut kepada Menag RI melalui Kepala Kantor Kemenag Pesisir Selatan.</p><p>"Terima kasih Pak Kemenag atas penghargaan ini," ucap Bupati Rusma Yul Anwar.&nbsp;</p><p>Dalam kesempatan itu kakan kemenag menyebutkan bahwa, penghargaan serupa juga diberikan Menag kepada 5 orang kepala daerah di Sumatera Barat. Diantaranya, Kabupaten Padang Pariaman, Kota Padang, Kota Bukittinggi, Tanah Datar dan Kabupaten Limapuluh Kota.&nbsp;</p><p>Bupati Rusma Yul Anwar dalam kesempatan itu juga menyerahkan Piagam Penghargaan kepada Syafri Dodi, Penyuluh Agama Islam (PAI) Kantor Urusan Agama (KUA) IV Jurai yang masuk Nomine 10 besar Penyuluh Agama Islam Award Tingkat Nasional 2023.</p><p>"Selamat untuk Syafri Dodi yang telah mengharumkan nama Pesisir Selatan di Tingkat Nasional. Semoga ke depan prestasi ini dapat ditingkatkan lagi," tutur Bupati.</p>',
                'keywords' => 'Penghargaan',
                'meta_desc' => 'Kakan Kemenag Pessel Serahkan Penghargaan Dari Menag Kepada Bupati',
                'is_news' => 'yes',
                'reads' => 2,
                'created_at' => '2023-08-30 23:17:18',
                'updated_at' => '2023-08-30 23:27:03',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'category_id' => 6,
                'user_id' => 1,
                'cover' => 'https://res.cloudinary.com/dezj1x6xp/image/upload/v1693412288/PandanViewMandeh/image_750x_64db4dcbc3a82_b89kkd.jpg',
                'title' => 'Serahkan SK PPPK, Abrar Munanda : Jalani Tugas Sesuai Dengan Yang Diamanahkan',
                'slug' => 'serahkan-sk-pppk-abrar-munanda-jalani-tugas-sesuai-dengan-yang-diamanahkan',
            'desc' => '<p>Sebanyak 29.069 Surat Keputusan (SK) pengangkatan Pegawai Pemerintah dengan Perjanjian Kerja (PPPK) Kementerian Agama Formasi Tahun 2022 diserahkan hari ini di masing-masing Satuan Kerja serentak nasional.</p><p>Pengambilan sumpah jabatan dan penyerahan Surat Keputusan Pengangkatan PPPK dilakukan secara simbolis oleh Menag Yaqut Cholil Qoumas. Acara dipusatkan di Auditorium HM Rasjidi, Gedung Kementerian Agama.&nbsp;</p><p>Seluruh satuan kerja yang juga akan menyerahkan SK mengikuti seremonial secara daring di daerahnya masing-masing.</p><p>Dalam arahannya Menag Yaqut mengucapkan selamat dan sukses kepada seluruh PPPK yang dilantik.</p><p>Menag menyampaikan kepada yang menerima SK agar selalu bersyukur, karena apa yang diterima ini adalah jawaban dari doa-doanya selama ini.</p><p>"Tetap ikhlas dalam memberikan pengabdian yang semakin luas kepada bangsa dan negara dalam pelayanan publik, terutama untuk keagamaan dan pendidikan," ungkap menag.</p><p>Kepala Kantor Kementerian Agama Kabupaten Pesisir Selatan, Abrar Munanda dalam arahannya dihadapan PPPK menyampaikan bahwa, pengukuhan dan pelantikan PPPK merupakan sebuah nikmat yang harus disyukuri.</p><p>"Hadir kita hari ini adalah momentum yang harus disyukuri atas apa yang telah dicapai. Jalani tugas sesuai dengan apa yang diamanahkan kepada kita," ujar Abrar Munanda.</p><p>Selain itu kata Abrar Munanda, laksanakan tugas dengan penuh tanggung jawab, ikhlas sesuai dengan simbol Kementerian Agama, yakni ikhlas beramal.</p><p>"Kemudian disiplin dan selalu mengembangkan serta harus ada kemauan menambah wawasan dalam melaksanakan tugas sebagai ASN," lanjut Abrar.</p><p>"Selamat bertugas di manapun ditempatkan, dan dapat menjadi contoh serta teladan di tempat kerja dan dilingkungan masyarakat. Torehlah prestasi-prestasi yang membanggakan," uajr Abrar menambahkan.</p><p>Sementara itu Analis SDM, Jarmil mengatakan, untuk Provinsi Sumatera Barat PPPK berjumlah 1579 orang, dan Kabupaten Pesisir Selatan 224 orang dari 924 orang yang mendaftar.</p><p>Jarmil menyampaikan kepada PPPK, setelah menerima SK agar segera melapor ke satuan kerja dan ke Kantor Kementerian Agama Kabupaten Pesisir dengan membawa dokumen untuk dimasukan ke dalam database ASN Kemenag.</p><p>Penyerahan SK PPPK tersebut dihadiri oleh perwakilan dari Kanwil Kemenag Provinsi Sumatera Barat, para pejabat dan ASN di lingkungan Kantor Kementerian Agama Kabupaten Pesisir Selatan.</p>',
                'keywords' => 'PPPK',
                'meta_desc' => 'Serahkan SK PPPK, Abrar Munanda : Jalani Tugas Sesuai Dengan Yang Diamanahkan',
                'is_news' => 'yes',
                'reads' => 0,
                'created_at' => '2023-08-30 23:18:12',
                'updated_at' => '2023-08-30 23:18:12',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'category_id' => 6,
                'user_id' => 1,
                'cover' => 'https://res.cloudinary.com/dezj1x6xp/image/upload/v1693412326/PandanViewMandeh/image_750x_64d36f2e2af68_q24pc4.jpg',
                'title' => 'Kunjungi Kemenag Pessel, Jubir Kemenag Apresiasi Layanan Kelompok Ramah Rentan',
                'slug' => 'kunjungi-kemenag-pessel-jubir-kemenag-apresiasi-layanan-kelompok-ramah-rentan',
            'desc' => '<p>Juru bicara (Jubir) Kementerian Agama RI, Anna Hasbie membahas sejumlah hal penting dalam kunjungannya ke Kantor Kementerian Agama Kabupaten Pesisir Selatan.</p><p>Kunjungan Jubir Kemenag ini disambut oleh Kepala Kantor Kementerian Agama Kabupaten Pesisir Selatan, Abrar Munanda di ruang kerjanya, Rabu (9/8/2023).</p><p>Dalam kunjungan ini, Anna Hasbie didampingi tim KSKK Ditjen Pendis dan Ketua Tim Sarpras Kanwil Kemenag Sumbar, Nofri Antoni membahas sejumlah hal penting. Diantaranya program madrasah inklusi.</p><p>Menanggapi hal tersebut, Abrar Munanda mengatakan, madrasah di Kabupaten Pesisir Selatan mempunyai 2 orang guru inklusi, satu orang merupakan CPNS 2018, dan satunya lagi adalah guru PPPK yang lulus formasi tahun 2022.</p><p>Anna Hasbie mengapresiasi penataan kantor Pelayanan Terpadu Satu Pintu Kemenag dan Pelayanan Ramah Kelompok Rentan Kantor Kementerian Agama Kabupaten Pesisir Selatan.</p><p>Apresiasi tersebut disampaikan saat mengunjungi pusat pelayanan publik tersebut.</p><p>Abrar Munanda menjelaskan tentang program layanan kelompok ramah rentan yang sedang diprioritaskan di Kantor Kementerian Agama Kabupaten Pesisir Selatan.</p><p>Selain itu kakan kemenag tersebut juga menerangkan program Jendela Hati, yang mana didalam program tersebut juga ada beberapa kegiatan terkait dengan penyelenggaraan ibadah haji.</p><p>"Dalam program jendela hati tersebut kita melaksanakan sapa jemaah haji melalui aplikasi zoom ketika jemaah haji persiapan ke Arafah, dan setelah di Arafah. Itu kita laksanakan bersama dengan Bupati dan Forkopimda," ungkapnya.</p><p>Terakhir Abrar Munanda menyampaikan terima kasih atas kunjungan Jubir Kemenag dan Tim KSKK. Abrar berharap hasil dari kunjungan, terkait apa yang disarankan akan dapat di laksanakan dengan baik sesuai yang diprogramkan.</p>',
                'keywords' => 'Kunjungan Kerja',
                'meta_desc' => 'Kunjungi Kemenag Pessel, Jubir Kemenag Apresiasi Layanan Kelompok Ramah Rentan',
                'is_news' => 'yes',
                'reads' => 0,
                'created_at' => '2023-08-30 23:19:07',
                'updated_at' => '2023-08-30 23:25:40',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'category_id' => 3,
                'user_id' => 1,
                'cover' => NULL,
                'title' => 'Regulasi',
                'slug' => 'regulasi',
            'desc' => '<h3><strong>Regulasi PPID</strong></h3><p>&nbsp;</p><h4>Peraturan</h4><p>Daftar peraturan terkait Keterbukaan Informasi Publik:</p><figure class="table"><table><tbody><tr><td>Undang-Undang (UU) Nomor 14 Tahun 2008 tentang Keterbukaan Informasi Publik</td><td><a href="https://ppid.kemenag.go.id/v3/files/60UU_No_14_Tahun_2008_tentang_KIP.pdf"><strong>link</strong></a></td></tr><tr><td>Peraturan Pemerintah (PP) No 61 Tahun 2010 tentang Pelaksanaan Undang - Undang Keterbukaan Informasi Publik</td><td><a href="https://ppid.kemenag.go.id/v3/files/12Nomor_61_Tahun_2010_Keterbukaan_Informasi_Publik.pdf"><strong>link</strong></a></td></tr><tr><td>Peraturan Komisi Informasi (PERKI) Nomor I Tahun 2021 tentang Standar Layanan Informasi Publik (SLIP)</td><td><a href="https://ppid.kemenag.go.id/v3/files/PerKIP%201%20Tahun%202021%20SLIP.pdf"><strong>link</strong></a></td></tr><tr><td>Peraturan Komisi Informasi (PERKI) Nomor 1 Tahun 2013 tentang Prosedur Penyelesaian Sengketa Informasi Publik</td><td><a href="https://ppid.kemenag.go.id/v3/files/40Perki_No.1_Tahun_2013_.pdf"><strong>link</strong></a></td></tr><tr><td>Peraturan Mahkamah Agung RI (Perma) Nomor 2 Tahun 2011 tentang Tata Cara Penyelesaian Sengketa Informasi Publik di Pengadilan</td><td><a href="https://ppid.kemenag.go.id/v3/files/6perma-no-2-tahun-2011-tentang-tata-cara-penyelesaian-sengketa-informasi-publik-pengadilan.pdf"><strong>link</strong></a></td></tr><tr><td>Keputusan Menteri Agama (KMA) Nomor 92 Tahun 2019 tentang Pedoman Layanan Informasi Publik Bagi Pejabat Pengelola Informasi dan Dokumentasi Kementerian Agama dan Atasan Pejabat Pengelola Informasi dan Dokumentasi Kementerian Agama</td><td><a href="https://ppid.kemenag.go.id/v3/files/33kma-92-2019-pedoman-layanan-publik-ppid-atasan-ppid.pdf"><strong>link</strong></a></td></tr><tr><td>Keputusan Menteri Agama Nomor 657 Tahun 2021 tentang PPID Kementerian Agama dan Atasan PPID Kementerian Agama</td><td><a href="https://ppid.kemenag.go.id/v3/files/Keputusan%20Menteri%20Agama%20Nomor%20657%20Tahun%202021%20tentang%20PPID%20Kementerian%20Agama%20dan%20Atasan%20PPID%20Kementerian%20Agama.pdf"><strong>link</strong></a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2">&nbsp;</td></tr></tbody></table></figure><p>&nbsp;</p><h4>Rancangan Peraturan</h4><p>Daftar rancangan peraturan terkait Keterbukaan Informasi Publik:</p><figure class="table"><table><tbody><tr><td>Rancangan Keputusan Menteri Agama Republik Indonesia tentang Pejabat Pengelola Informasi dan Dokumentasi Kementerian Agama dan Atasan Pejabat Pengelola Informasi dan Dokumentasi</td><td><a href="https://ppid.kemenag.go.id/v3/files/64Draft-KMA-PPID-dan-Atasan-PPID-Kemenag.pdf"><strong>link</strong></a></td></tr><tr><td>Rancangan Keputusan Menteri Agama Republik Indonesia tentang Pedoman Layanan Informasi Publik Bagi Pejabat Pengelola Informasi dan Dokumentasi Kementerian Agama dan Atasan Pejabat Pengelola Informasi dan Dokumentasi Kementerian Agama</td><td><a href="https://ppid.kemenag.go.id/v3/files/22018-12-06-Draft%20KMA%20ttg%20Pedoman%20Layanan%20Informasi%20Publik%20di%20Kemenag-edit%20final%20sblm%20ke%20rohukum.pdf"><strong>link</strong></a></td></tr></tbody></table></figure>',
                'keywords' => 'Regulasi',
                'meta_desc' => 'Regulasi',
                'is_news' => 'no',
                'reads' => 32,
                'created_at' => '2023-08-31 00:41:55',
                'updated_at' => '2023-08-31 19:44:52',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'category_id' => 1,
                'user_id' => 1,
                'cover' => NULL,
                'title' => 'e-PPID Mobile',
                'slug' => 'e-ppid-mobile',
                'desc' => '<p>Aplikasi ini merupakan sarana yang disediakan oleh Pejabat Pengelola Informasi dan Dokumentasi Kementerian Agama kepada masyarakat untuk memberikan kemudahan mendapatkan layanan Informasi Publik kapan saja dan dimana saja. Unduh aplikasi mobile-PPID Kementerian Agama di Play Store.</p><p>&nbsp;</p><p><a href="https://ppid.kemenag.go.id/v4/apk/PPIDKemenag.apk"><strong><img src="https://ppid.kemenag.go.id/v4/images/google-play-logo.png"></strong></a></p><p>&nbsp;</p>',
                'keywords' => 'e-PPID Mobile',
                'meta_desc' => 'e-PPID Mobile',
                'is_news' => 'no',
                'reads' => 13,
                'created_at' => '2023-08-31 19:26:29',
                'updated_at' => '2023-09-01 10:27:26',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'category_id' => 5,
                'user_id' => 1,
                'cover' => NULL,
                'title' => 'SOP Layanan Informasi Publik',
                'slug' => 'sop-layanan-informasi-publik',
            'desc' => '<p>Daftar SOP (Standar Operasional Prosedur) Layanan Informasi Publik:</p><figure class="table"><table><tbody><tr><td>Standar Operasional Prosedur Pengelolaan Permohonan Informasi</td><td><a href="https://ppid.kemenag.go.id/v3/files/76SOP%20Pengelolaan%20Permohonan%20Informasi.pdf"><strong>get</strong></a></td></tr><tr><td>SStandar Operasional Prosedur Pengelolaan Keberatan</td><td><a href="https://ppid.kemenag.go.id/v3/files/41SOP%20Pengelolaan%20Keberatan%20Atas%20Informasi.pdf"><strong>get</strong></a></td></tr><tr><td>Standar Operasional Prosedur Penanganan Sengketa Informasi</td><td><a href="https://ppid.kemenag.go.id/v3/files/76SOP%20Penanganan%20Sengketa%20Informasi%20Publik.pdf"><strong>get</strong></a></td></tr><tr><td>Standar Operasional Prosedur Penetapan dan Pemutakhiran DIP</td><td><a href="https://ppid.kemenag.go.id/v3/files/82SOP%20Penetapan%20dan%20Pemutakhiran%20DIP.pdf"><strong>get</strong></a></td></tr><tr><td>Standar Operasional Prosedur Pendokumentasian Informasi Publik</td><td><a href="https://ppid.kemenag.go.id/v3/files/38SOP%20Pendokumentasian%20Informasi%20Publik.pdf"><strong>get</strong></a></td></tr><tr><td>Standar Operasional Prosedur Pengujian Konsekuensi</td><td><a href="https://ppid.kemenag.go.id/v3/files/28SOP%20Pengujian%20konsekuensi.pdf"><strong>get</strong></a></td></tr><tr><td>Standar Operasional Prosedur Pendokumentasian Informasi yang Dikecualikan</td><td><a href="https://ppid.kemenag.go.id/v3/files/84SOP%20Pendokumentasian%20Informasi%20yang%20Dikecualikan.pdf"><strong>get</strong></a></td></tr></tbody></table></figure>',
                'keywords' => 'SOP Layanan Informasi Publik',
                'meta_desc' => 'SOP Layanan Informasi Publik',
                'is_news' => 'no',
                'reads' => 0,
                'created_at' => '2023-08-31 19:30:25',
                'updated_at' => '2023-08-31 19:30:25',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'category_id' => 5,
                'user_id' => 1,
                'cover' => NULL,
                'title' => 'Standar Pengumuman Informasi',
                'slug' => 'standar-pengumuman-informasi',
            'desc' => '<p>Standar Pengumuman Informasi pada Kementerian Agama Pusat, Perguruan Tinggi Keagamaan Negeri (PTKN), Kantor Wilayah Kementerian Agama Provinsi, Kantor Kementerian Agama Kabupaten/Kota, Balai Litbang Agama, Balai Diklat Keagamaan, dan KUA Kecamatan.</p><p><br>1. Pengumuman informasi <strong>wajib</strong> memenuhi:<br> &nbsp;a) menggunakan bahasa Indonesia yang baik dan benar;<br> &nbsp;b) mudah dipahami; dan<br> &nbsp;c) mempertimbangkan penggunaan bahasa yang digunakan penduduk setempat.</p><p><br>2. Pengumuman informasi disebarluaskan melalui:<br> &nbsp;a) papan pengumuman;<br> &nbsp;b) laman resmi (Website) PPID dan/atau Badan Publik;<br> &nbsp;c) media sosial PPID dan/atau Badan Publik;<br> &nbsp;d) Portal Satu Data Indonesia; dan/atau<br> &nbsp;e) Aplikasi berbasis teknologi informasi;</p><p><br>3. Pengumuman dan penyebarluasan Informasi Publik <strong>wajib</strong> memperhatikan Aksesibilitas bagi Penyandang Disabilitas.</p><p><br>4. Pengumuman dan penyebarluasan Informasi Publik paling sedikit dilengkapi dengan audio, visual, dan/atau <i>braille</i>.</p>',
                'keywords' => 'Standar Pengumuman Informasi',
                'meta_desc' => 'Standar Pengumuman Informasi',
                'is_news' => 'no',
                'reads' => 0,
                'created_at' => '2023-08-31 19:31:47',
                'updated_at' => '2023-08-31 19:31:47',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}