<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PostViewsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('post_views')->delete();
        
        \DB::table('post_views')->insert(array (
            0 => 
            array (
                'id' => 1,
                'post_id' => 7,
                'slug' => 'menjelajahi-dunia-melalui-pariwisata-merayakan-keajaiban-alam-dan-budaya',
                'url' => 'https://pandanviewmandeh.com/post/menjelajahi-dunia-melalui-pariwisata-merayakan-keajaiban-alam-dan-budaya',
                'session_id' => 'SNaqcfp29HGcnW9uGFSapM6cKg0ki6XBaPUp8NBe',
                'user_id' => NULL,
                'ip' => '36.69.8.206',
            'agent' => 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36',
                'created_at' => '2023-07-12 15:48:35',
                'updated_at' => '2023-07-12 15:48:35',
            ),
            1 => 
            array (
                'id' => 2,
                'post_id' => 4,
                'slug' => 'kemenag-pessel-gelar-raker-tahun-2022-di-pandan-view-kawasan-mandeh',
                'url' => 'https://pandanviewmandeh.com/post/kemenag-pessel-gelar-raker-tahun-2022-di-pandan-view-kawasan-mandeh',
                'session_id' => '5Ms4hIJiv6wnvR6hmCCt2zwqjPKAbMSjNP1la7sm',
                'user_id' => NULL,
                'ip' => '66.249.65.171',
                'agent' => 'Mediapartners-Google',
                'created_at' => '2023-07-12 17:18:39',
                'updated_at' => '2023-07-12 17:18:39',
            ),
            2 => 
            array (
                'id' => 3,
                'post_id' => 1,
                'slug' => 'menikmati-lezatnya-snack-di-pandan-view-mandeh',
                'url' => 'https://pandanviewmandeh.com/post/menikmati-lezatnya-snack-di-pandan-view-mandeh',
                'session_id' => 'XOUanI6ZucYrlJsl2IYNtuWVgsqtYUfCTxTptWZI',
                'user_id' => NULL,
                'ip' => '66.249.65.171',
                'agent' => 'Mediapartners-Google',
                'created_at' => '2023-07-12 17:18:40',
                'updated_at' => '2023-07-12 17:18:40',
            ),
            3 => 
            array (
                'id' => 4,
                'post_id' => 7,
                'slug' => 'menjelajahi-dunia-melalui-pariwisata-merayakan-keajaiban-alam-dan-budaya',
                'url' => 'https://pandanviewmandeh.com/post/menjelajahi-dunia-melalui-pariwisata-merayakan-keajaiban-alam-dan-budaya',
                'session_id' => '8uu8Eas4d7YqkGlMNoBgZdgZ2kLBibD2f4MYGTd6',
                'user_id' => NULL,
                'ip' => '66.249.65.171',
                'agent' => 'Mediapartners-Google',
                'created_at' => '2023-07-12 17:18:43',
                'updated_at' => '2023-07-12 17:18:43',
            ),
            4 => 
            array (
                'id' => 5,
                'post_id' => 3,
                'slug' => 'pandan-view-mandeh',
                'url' => 'https://pandanviewmandeh.com/post/pandan-view-mandeh',
                'session_id' => '3CduEDd9LQtqYwTOaNbumG5iPcQwGvPiV5XUEuLt',
                'user_id' => NULL,
                'ip' => '66.249.65.171',
                'agent' => 'Mediapartners-Google',
                'created_at' => '2023-07-12 17:18:45',
                'updated_at' => '2023-07-12 17:18:45',
            ),
            5 => 
            array (
                'id' => 6,
                'post_id' => 6,
                'slug' => 'pandan-view-mandeh-keindahan-puncak-mandeh-yang-menakjubkan',
                'url' => 'https://pandanviewmandeh.com/post/pandan-view-mandeh-keindahan-puncak-mandeh-yang-menakjubkan',
                'session_id' => 'pgv9ezHQMHqcfjEEi06F8JnHopq3EM9JIBNASZ8u',
                'user_id' => NULL,
                'ip' => '66.249.65.171',
                'agent' => 'Mediapartners-Google',
                'created_at' => '2023-07-12 17:18:46',
                'updated_at' => '2023-07-12 17:18:46',
            ),
            6 => 
            array (
                'id' => 7,
                'post_id' => 5,
                'slug' => 'perbedaan-hotel-bungalow-resort-cottage-dan-villa',
                'url' => 'https://pandanviewmandeh.com/post/perbedaan-hotel-bungalow-resort-cottage-dan-villa',
                'session_id' => 'ngiIp1koKLVnR1Ej4W5bc3DwPbvFABc369dO6JGR',
                'user_id' => NULL,
                'ip' => '66.249.65.171',
                'agent' => 'Mediapartners-Google',
                'created_at' => '2023-07-12 17:18:48',
                'updated_at' => '2023-07-12 17:18:48',
            ),
            7 => 
            array (
                'id' => 8,
                'post_id' => 2,
                'slug' => 'tips-traveling-di-sumatera-barat-menikmati-keindahan-alam-dan-budaya',
                'url' => 'https://pandanviewmandeh.com/post/tips-traveling-di-sumatera-barat-menikmati-keindahan-alam-dan-budaya',
                'session_id' => '43AR8xKwDfaBOarueVbIK1ojFXihL7PFhL0ahoCU',
                'user_id' => NULL,
                'ip' => '66.249.65.171',
                'agent' => 'Mediapartners-Google',
                'created_at' => '2023-07-12 17:18:49',
                'updated_at' => '2023-07-12 17:18:49',
            ),
            8 => 
            array (
                'id' => 9,
                'post_id' => 4,
                'slug' => 'kemenag-pessel-gelar-raker-tahun-2022-di-pandan-view-kawasan-mandeh',
                'url' => 'http://www.pandanviewmandeh.com/post/kemenag-pessel-gelar-raker-tahun-2022-di-pandan-view-kawasan-mandeh',
                'session_id' => 'tn1kzrytuXDLc0ODQoNpqbfGgsJK1oBZiZuZFpMU',
                'user_id' => NULL,
                'ip' => '66.249.73.228',
                'agent' => 'Mediapartners-Google',
                'created_at' => '2023-07-12 17:19:15',
                'updated_at' => '2023-07-12 17:19:15',
            ),
            9 => 
            array (
                'id' => 10,
                'post_id' => 1,
                'slug' => 'menikmati-lezatnya-snack-di-pandan-view-mandeh',
                'url' => 'http://www.pandanviewmandeh.com/post/menikmati-lezatnya-snack-di-pandan-view-mandeh',
                'session_id' => 'h90va2g0IKva6JnXVPqj7ZNJCIMsepSVFfDO9p5K',
                'user_id' => NULL,
                'ip' => '66.249.73.228',
                'agent' => 'Mediapartners-Google',
                'created_at' => '2023-07-12 17:19:17',
                'updated_at' => '2023-07-12 17:19:17',
            ),
            10 => 
            array (
                'id' => 11,
                'post_id' => 7,
                'slug' => 'menjelajahi-dunia-melalui-pariwisata-merayakan-keajaiban-alam-dan-budaya',
                'url' => 'http://www.pandanviewmandeh.com/post/menjelajahi-dunia-melalui-pariwisata-merayakan-keajaiban-alam-dan-budaya',
                'session_id' => 'Pdba54BtzdMbS7urINfYZnwsd3KblTBQHuHqVWC0',
                'user_id' => NULL,
                'ip' => '66.249.73.228',
                'agent' => 'Mediapartners-Google',
                'created_at' => '2023-07-12 17:19:19',
                'updated_at' => '2023-07-12 17:19:19',
            ),
            11 => 
            array (
                'id' => 12,
                'post_id' => 3,
                'slug' => 'pandan-view-mandeh',
                'url' => 'http://www.pandanviewmandeh.com/post/pandan-view-mandeh',
                'session_id' => 'Pnzt84tuwI4xCHUGnEb64YdSYFuud15ziNRStIHo',
                'user_id' => NULL,
                'ip' => '66.249.73.228',
                'agent' => 'Mediapartners-Google',
                'created_at' => '2023-07-12 17:19:20',
                'updated_at' => '2023-07-12 17:19:20',
            ),
            12 => 
            array (
                'id' => 13,
                'post_id' => 6,
                'slug' => 'pandan-view-mandeh-keindahan-puncak-mandeh-yang-menakjubkan',
                'url' => 'http://www.pandanviewmandeh.com/post/pandan-view-mandeh-keindahan-puncak-mandeh-yang-menakjubkan',
                'session_id' => '2EW9ajKbmtv4FafMJf5R8NSquMkgm6m11Cb9SINj',
                'user_id' => NULL,
                'ip' => '66.249.73.228',
                'agent' => 'Mediapartners-Google',
                'created_at' => '2023-07-12 17:19:22',
                'updated_at' => '2023-07-12 17:19:22',
            ),
            13 => 
            array (
                'id' => 14,
                'post_id' => 5,
                'slug' => 'perbedaan-hotel-bungalow-resort-cottage-dan-villa',
                'url' => 'http://www.pandanviewmandeh.com/post/perbedaan-hotel-bungalow-resort-cottage-dan-villa',
                'session_id' => '371oWx5CLOzTVCpieATsBiFeekHplVHtMKtLgTPo',
                'user_id' => NULL,
                'ip' => '66.249.73.228',
                'agent' => 'Mediapartners-Google',
                'created_at' => '2023-07-12 17:19:24',
                'updated_at' => '2023-07-12 17:19:24',
            ),
            14 => 
            array (
                'id' => 15,
                'post_id' => 2,
                'slug' => 'tips-traveling-di-sumatera-barat-menikmati-keindahan-alam-dan-budaya',
                'url' => 'http://www.pandanviewmandeh.com/post/tips-traveling-di-sumatera-barat-menikmati-keindahan-alam-dan-budaya',
                'session_id' => 'ZJzy8slC53erX8dnco4T8M3KmQELnEamKDXZOYNp',
                'user_id' => NULL,
                'ip' => '66.249.73.228',
                'agent' => 'Mediapartners-Google',
                'created_at' => '2023-07-12 17:19:25',
                'updated_at' => '2023-07-12 17:19:25',
            ),
            15 => 
            array (
                'id' => 16,
                'post_id' => 2,
                'slug' => 'tips-traveling-di-sumatera-barat-menikmati-keindahan-alam-dan-budaya',
                'url' => 'https://pandanviewmandeh.com/post/tips-traveling-di-sumatera-barat-menikmati-keindahan-alam-dan-budaya',
                'session_id' => 'W1Ivk02pVbsYnEZJPUU3CG3XzyJA9SqI3CaSawWm',
                'user_id' => NULL,
                'ip' => '66.249.79.12',
            'agent' => 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
                'created_at' => '2023-07-12 19:50:57',
                'updated_at' => '2023-07-12 19:50:57',
            ),
            16 => 
            array (
                'id' => 17,
                'post_id' => 4,
                'slug' => 'kemenag-pessel-gelar-raker-tahun-2022-di-pandan-view-kawasan-mandeh',
                'url' => 'http://www.pandanviewmandeh.com/post/kemenag-pessel-gelar-raker-tahun-2022-di-pandan-view-kawasan-mandeh',
                'session_id' => 'youAje1p2OTsyj9bOIromSlGKoaAsL7TANcJjQll',
                'user_id' => NULL,
                'ip' => '66.249.71.166',
            'agent' => 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
                'created_at' => '2023-07-12 19:53:17',
                'updated_at' => '2023-07-12 19:53:17',
            ),
            17 => 
            array (
                'id' => 18,
                'post_id' => 5,
                'slug' => 'perbedaan-hotel-bungalow-resort-cottage-dan-villa',
                'url' => 'https://pandanviewmandeh.com/post/perbedaan-hotel-bungalow-resort-cottage-dan-villa',
                'session_id' => 'gzWu4W2Ak6tzCdAK7pBN4tJrJ85WVhWP2abH2Ndf',
                'user_id' => NULL,
                'ip' => '66.249.71.67',
            'agent' => 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
                'created_at' => '2023-07-12 19:53:56',
                'updated_at' => '2023-07-12 19:53:56',
            ),
            18 => 
            array (
                'id' => 19,
                'post_id' => 6,
                'slug' => 'pandan-view-mandeh-keindahan-puncak-mandeh-yang-menakjubkan',
                'url' => 'https://pandanviewmandeh.com/post/pandan-view-mandeh-keindahan-puncak-mandeh-yang-menakjubkan',
                'session_id' => '8HzxHEl0A9SrJHobrLlJbSmuZAaa7tyx3cqXvqh8',
                'user_id' => NULL,
                'ip' => '66.249.79.12',
            'agent' => 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
                'created_at' => '2023-07-12 19:54:17',
                'updated_at' => '2023-07-12 19:54:17',
            ),
            19 => 
            array (
                'id' => 20,
                'post_id' => 1,
                'slug' => 'menikmati-lezatnya-snack-di-pandan-view-mandeh',
                'url' => 'http://www.pandanviewmandeh.com/post/menikmati-lezatnya-snack-di-pandan-view-mandeh',
                'session_id' => 'dz6ccAVRzDkwXW4YnAjZB7jnDfKPLV3ptzRwpCht',
                'user_id' => NULL,
                'ip' => '66.249.71.164',
            'agent' => 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
                'created_at' => '2023-07-12 19:54:36',
                'updated_at' => '2023-07-12 19:54:36',
            ),
            20 => 
            array (
                'id' => 21,
                'post_id' => 7,
                'slug' => 'menjelajahi-dunia-melalui-pariwisata-merayakan-keajaiban-alam-dan-budaya',
                'url' => 'https://pandanviewmandeh.com/post/menjelajahi-dunia-melalui-pariwisata-merayakan-keajaiban-alam-dan-budaya',
                'session_id' => 'j7ieuqichmmdhArn1AxnSt0zwjb31gu7GbIIuM7G',
                'user_id' => NULL,
                'ip' => '66.249.71.68',
            'agent' => 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
                'created_at' => '2023-07-12 19:55:36',
                'updated_at' => '2023-07-12 19:55:36',
            ),
            21 => 
            array (
                'id' => 22,
                'post_id' => 4,
                'slug' => 'kemenag-pessel-gelar-raker-tahun-2022-di-pandan-view-kawasan-mandeh',
                'url' => 'http://www.pandanviewmandeh.com/post/kemenag-pessel-gelar-raker-tahun-2022-di-pandan-view-kawasan-mandeh',
                'session_id' => 'gRaPVuyh4g1ucGHDWYMSxGBq8EmIjv6vuOKgdId7',
                'user_id' => NULL,
                'ip' => '66.249.71.164',
            'agent' => 'Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.179 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
                'created_at' => '2023-07-12 19:55:56',
                'updated_at' => '2023-07-12 19:55:56',
            ),
            22 => 
            array (
                'id' => 23,
                'post_id' => 1,
                'slug' => 'menikmati-lezatnya-snack-di-pandan-view-mandeh',
                'url' => 'http://www.pandanviewmandeh.com/post/menikmati-lezatnya-snack-di-pandan-view-mandeh',
                'session_id' => 'rbLpJ0kkv7CH6DR0mzPehiprpoh9KFfy5Q2vRKre',
                'user_id' => NULL,
                'ip' => '66.249.68.34',
            'agent' => 'Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.179 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
                'created_at' => '2023-07-12 19:57:16',
                'updated_at' => '2023-07-12 19:57:16',
            ),
            23 => 
            array (
                'id' => 24,
                'post_id' => 5,
                'slug' => 'perbedaan-hotel-bungalow-resort-cottage-dan-villa',
                'url' => 'https://pandanviewmandeh.com/post/perbedaan-hotel-bungalow-resort-cottage-dan-villa',
                'session_id' => 'FDikPwWvegEz5E6XOaz2YWjR1vPhOjBTPV5HdoXd',
                'user_id' => NULL,
                'ip' => '66.249.71.205',
            'agent' => 'Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.179 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
                'created_at' => '2023-07-12 19:57:36',
                'updated_at' => '2023-07-12 19:57:36',
            ),
            24 => 
            array (
                'id' => 25,
                'post_id' => 2,
                'slug' => 'tips-traveling-di-sumatera-barat-menikmati-keindahan-alam-dan-budaya',
                'url' => 'https://pandanviewmandeh.com/post/tips-traveling-di-sumatera-barat-menikmati-keindahan-alam-dan-budaya',
                'session_id' => 'y36mjXKNymUg6OdfBHoPKbANtxgIdTYXDqjzWVfE',
                'user_id' => NULL,
                'ip' => '66.249.71.68',
            'agent' => 'Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.179 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
                'created_at' => '2023-07-12 19:57:56',
                'updated_at' => '2023-07-12 19:57:56',
            ),
            25 => 
            array (
                'id' => 26,
                'post_id' => 6,
                'slug' => 'pandan-view-mandeh-keindahan-puncak-mandeh-yang-menakjubkan',
                'url' => 'https://pandanviewmandeh.com/post/pandan-view-mandeh-keindahan-puncak-mandeh-yang-menakjubkan',
                'session_id' => 'Kl3YUT3nS4NDhtz3F97PC8BQtcemTgGKdtFMs9vG',
                'user_id' => NULL,
                'ip' => '66.249.79.13',
            'agent' => 'Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.179 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
                'created_at' => '2023-07-12 19:58:16',
                'updated_at' => '2023-07-12 19:58:16',
            ),
            26 => 
            array (
                'id' => 27,
                'post_id' => 3,
                'slug' => 'pandan-view-mandeh',
                'url' => 'http://pandanviewmandeh.com/post/pandan-view-mandeh',
                'session_id' => 'qtfF2uxaaCscV7UuLmCVnlag1j6ZHHLIza7PVsYp',
                'user_id' => NULL,
                'ip' => '66.249.71.70',
            'agent' => 'Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.179 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
                'created_at' => '2023-07-13 06:42:23',
                'updated_at' => '2023-07-13 06:42:23',
            ),
            27 => 
            array (
                'id' => 28,
                'post_id' => 3,
                'slug' => 'pandan-view-mandeh',
                'url' => 'http://pandanviewmandeh.com/post/pandan-view-mandeh',
                'session_id' => 'y2P3cL8bTjyy1v0f7JL8gSumRgjhtOjcOxtjay9X',
                'user_id' => NULL,
                'ip' => '66.249.71.71',
            'agent' => 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
                'created_at' => '2023-07-13 07:15:12',
                'updated_at' => '2023-07-13 07:15:12',
            ),
            28 => 
            array (
                'id' => 29,
                'post_id' => 8,
                'slug' => 'menguasai-sales-dan-marketing-di-industri-pariwisata-strategi-sukses-untuk-menggaet-pengunjung-dan-meningkatkan-penjualan',
                'url' => 'https://pandanviewmandeh.com/post/menguasai-sales-dan-marketing-di-industri-pariwisata-strategi-sukses-untuk-menggaet-pengunjung-dan-meningkatkan-penjualan',
                'session_id' => '4WkfP3rDhFXKFlQ3CSwDU5TnBgqVF415BbuTKeeK',
                'user_id' => 1,
                'ip' => '36.69.8.206',
            'agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0',
                'created_at' => '2023-07-13 08:44:22',
                'updated_at' => '2023-07-13 08:44:22',
            ),
            29 => 
            array (
                'id' => 30,
                'post_id' => 5,
                'slug' => 'perbedaan-hotel-bungalow-resort-cottage-dan-villa',
                'url' => 'https://pandanviewmandeh.com/post/perbedaan-hotel-bungalow-resort-cottage-dan-villa',
                'session_id' => 'uc1MeNtZMk44p4fwiYhibjS5cq6CTuMmVWvDfYcl',
                'user_id' => 1,
                'ip' => '36.69.8.206',
            'agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0',
                'created_at' => '2023-07-13 08:47:58',
                'updated_at' => '2023-07-13 08:47:58',
            ),
            30 => 
            array (
                'id' => 31,
                'post_id' => 1,
                'slug' => 'menikmati-lezatnya-snack-di-pandan-view-mandeh',
                'url' => 'http://pandanviewmandeh.com/post/menikmati-lezatnya-snack-di-pandan-view-mandeh',
                'session_id' => '0vFKnp35MIZHDozfadmdcINxU1cfbIgfUgMzHKuT',
                'user_id' => NULL,
                'ip' => '85.92.66.148',
            'agent' => 'Mozilla/5.0 (compatible; XML Sitemaps Generator; www.xml-sitemaps.com) Gecko XML-Sitemaps/1.0',
                'created_at' => '2023-07-13 10:38:43',
                'updated_at' => '2023-07-13 10:38:43',
            ),
            31 => 
            array (
                'id' => 32,
                'post_id' => 2,
                'slug' => 'tips-traveling-di-sumatera-barat-menikmati-keindahan-alam-dan-budaya',
                'url' => 'http://pandanviewmandeh.com/post/tips-traveling-di-sumatera-barat-menikmati-keindahan-alam-dan-budaya',
                'session_id' => 'jklJ5MY39T1ztiNrYBH5SFMY7QFMG3jDyYrFoxSK',
                'user_id' => NULL,
                'ip' => '85.92.66.148',
            'agent' => 'Mozilla/5.0 (compatible; XML Sitemaps Generator; www.xml-sitemaps.com) Gecko XML-Sitemaps/1.0',
                'created_at' => '2023-07-13 10:38:43',
                'updated_at' => '2023-07-13 10:38:43',
            ),
            32 => 
            array (
                'id' => 33,
                'post_id' => 3,
                'slug' => 'pandan-view-mandeh-resort',
                'url' => 'http://pandanviewmandeh.com/post/pandan-view-mandeh-resort',
                'session_id' => 'EtSBBnp2WJut1CED8bnKhifrmbnSKRGPpEbFcoRt',
                'user_id' => NULL,
                'ip' => '85.92.66.148',
            'agent' => 'Mozilla/5.0 (compatible; XML Sitemaps Generator; www.xml-sitemaps.com) Gecko XML-Sitemaps/1.0',
                'created_at' => '2023-07-13 10:38:44',
                'updated_at' => '2023-07-13 10:38:44',
            ),
            33 => 
            array (
                'id' => 34,
                'post_id' => 4,
                'slug' => 'kemenag-pessel-gelar-raker-tahun-2022-di-pandan-view-kawasan-mandeh',
                'url' => 'http://pandanviewmandeh.com/post/kemenag-pessel-gelar-raker-tahun-2022-di-pandan-view-kawasan-mandeh',
                'session_id' => 'EtKD3fK91nkCcZ7QAGM09pDpNjVJSka37shkGuLo',
                'user_id' => NULL,
                'ip' => '85.92.66.148',
            'agent' => 'Mozilla/5.0 (compatible; XML Sitemaps Generator; www.xml-sitemaps.com) Gecko XML-Sitemaps/1.0',
                'created_at' => '2023-07-13 10:38:45',
                'updated_at' => '2023-07-13 10:38:45',
            ),
            34 => 
            array (
                'id' => 35,
                'post_id' => 5,
                'slug' => 'perbedaan-hotel-bungalow-resort-cottage-dan-villa',
                'url' => 'http://pandanviewmandeh.com/post/perbedaan-hotel-bungalow-resort-cottage-dan-villa',
                'session_id' => 'IMFDByYDzf4bRwEsSixoXRaH6IrTLSbAvxEaw1Xj',
                'user_id' => NULL,
                'ip' => '85.92.66.148',
            'agent' => 'Mozilla/5.0 (compatible; XML Sitemaps Generator; www.xml-sitemaps.com) Gecko XML-Sitemaps/1.0',
                'created_at' => '2023-07-13 10:38:45',
                'updated_at' => '2023-07-13 10:38:45',
            ),
            35 => 
            array (
                'id' => 36,
                'post_id' => 10,
                'slug' => 'misteri-menyelubungi-rumah-gadang-mande-rubiyah-keajaiban-arsitektur-dengan-kisah-yang-tersimpan',
                'url' => 'http://pandanviewmandeh.com/post/misteri-menyelubungi-rumah-gadang-mande-rubiyah-keajaiban-arsitektur-dengan-kisah-yang-tersimpan',
                'session_id' => 'ZvGFw5pBjqtbwlbJTva5O8VtHhXFsftHz9yWJRGX',
                'user_id' => NULL,
                'ip' => '85.92.66.148',
            'agent' => 'Mozilla/5.0 (compatible; XML Sitemaps Generator; www.xml-sitemaps.com) Gecko XML-Sitemaps/1.0',
                'created_at' => '2023-07-13 10:38:46',
                'updated_at' => '2023-07-13 10:38:46',
            ),
            36 => 
            array (
                'id' => 37,
                'post_id' => 9,
                'slug' => 'keindahan-lautan-yang-menakjubkan-eksplorasi-gugusan-mandeh-di-sumatera-barat',
                'url' => 'http://pandanviewmandeh.com/post/keindahan-lautan-yang-menakjubkan-eksplorasi-gugusan-mandeh-di-sumatera-barat',
                'session_id' => 'XARUl1ykUspcPdjFQW4GWHpzxP1MhtX2zNM082y0',
                'user_id' => NULL,
                'ip' => '85.92.66.148',
            'agent' => 'Mozilla/5.0 (compatible; XML Sitemaps Generator; www.xml-sitemaps.com) Gecko XML-Sitemaps/1.0',
                'created_at' => '2023-07-13 10:38:46',
                'updated_at' => '2023-07-13 10:38:46',
            ),
            37 => 
            array (
                'id' => 38,
                'post_id' => 8,
                'slug' => 'menguasai-sales-dan-marketing-di-industri-pariwisata-strategi-sukses-untuk-menggaet-pengunjung-dan-meningkatkan-penjualan',
                'url' => 'http://pandanviewmandeh.com/post/menguasai-sales-dan-marketing-di-industri-pariwisata-strategi-sukses-untuk-menggaet-pengunjung-dan-meningkatkan-penjualan',
                'session_id' => 'BnV7HbGhXdRkUCPEoeE7ufWDmGjRJmJUoJdZLQA4',
                'user_id' => NULL,
                'ip' => '85.92.66.148',
            'agent' => 'Mozilla/5.0 (compatible; XML Sitemaps Generator; www.xml-sitemaps.com) Gecko XML-Sitemaps/1.0',
                'created_at' => '2023-07-13 10:38:47',
                'updated_at' => '2023-07-13 10:38:47',
            ),
            38 => 
            array (
                'id' => 39,
                'post_id' => 7,
                'slug' => 'menjelajahi-dunia-melalui-pariwisata-merayakan-keajaiban-alam-dan-budaya',
                'url' => 'http://pandanviewmandeh.com/post/menjelajahi-dunia-melalui-pariwisata-merayakan-keajaiban-alam-dan-budaya',
                'session_id' => 'JOCgBe2v2T7XVNqbnkZLRrYyG5tCDXYmdnm8Wu6E',
                'user_id' => NULL,
                'ip' => '85.92.66.148',
            'agent' => 'Mozilla/5.0 (compatible; XML Sitemaps Generator; www.xml-sitemaps.com) Gecko XML-Sitemaps/1.0',
                'created_at' => '2023-07-13 10:38:47',
                'updated_at' => '2023-07-13 10:38:47',
            ),
            39 => 
            array (
                'id' => 40,
                'post_id' => 6,
                'slug' => 'pandan-view-mandeh-keindahan-puncak-mandeh-yang-menakjubkan',
                'url' => 'http://pandanviewmandeh.com/post/pandan-view-mandeh-keindahan-puncak-mandeh-yang-menakjubkan',
                'session_id' => 'VxZkq61YTwOOFID8o50Z3AcX5XqAMqUqFOkARPNl',
                'user_id' => NULL,
                'ip' => '85.92.66.148',
            'agent' => 'Mozilla/5.0 (compatible; XML Sitemaps Generator; www.xml-sitemaps.com) Gecko XML-Sitemaps/1.0',
                'created_at' => '2023-07-13 10:38:54',
                'updated_at' => '2023-07-13 10:38:54',
            ),
            40 => 
            array (
                'id' => 41,
                'post_id' => 1,
                'slug' => 'menikmati-lezatnya-snack-di-pandan-view-mandeh',
                'url' => 'https://pandanviewmandeh.com/post/menikmati-lezatnya-snack-di-pandan-view-mandeh',
                'session_id' => 'xsqgn0HwQvdE6hnoNsSsTBByxLwV3uOgeACVbJxs',
                'user_id' => NULL,
                'ip' => '35.203.251.13',
            'agent' => 'Mozilla/5.0 (compatible; XML sitemap generator; octopus.do) Gecko Octopus/1.0',
                'created_at' => '2023-07-13 10:41:06',
                'updated_at' => '2023-07-13 10:41:06',
            ),
            41 => 
            array (
                'id' => 42,
                'post_id' => 2,
                'slug' => 'tips-traveling-di-sumatera-barat-menikmati-keindahan-alam-dan-budaya',
                'url' => 'https://pandanviewmandeh.com/post/tips-traveling-di-sumatera-barat-menikmati-keindahan-alam-dan-budaya',
                'session_id' => 'ezQDECSKLLy4gDZYoDg7WjuJh3etdBFEvkhojCOb',
                'user_id' => NULL,
                'ip' => '35.203.251.13',
            'agent' => 'Mozilla/5.0 (compatible; XML sitemap generator; octopus.do) Gecko Octopus/1.0',
                'created_at' => '2023-07-13 10:41:07',
                'updated_at' => '2023-07-13 10:41:07',
            ),
            42 => 
            array (
                'id' => 43,
                'post_id' => 3,
                'slug' => 'pandan-view-mandeh-resort',
                'url' => 'https://pandanviewmandeh.com/post/pandan-view-mandeh-resort',
                'session_id' => 'qGV0CXjbqPaGGABgnulsvDxnM3tRmCGDbTrma8lo',
                'user_id' => NULL,
                'ip' => '35.203.251.13',
            'agent' => 'Mozilla/5.0 (compatible; XML sitemap generator; octopus.do) Gecko Octopus/1.0',
                'created_at' => '2023-07-13 10:41:07',
                'updated_at' => '2023-07-13 10:41:07',
            ),
            43 => 
            array (
                'id' => 44,
                'post_id' => 4,
                'slug' => 'kemenag-pessel-gelar-raker-tahun-2022-di-pandan-view-kawasan-mandeh',
                'url' => 'https://pandanviewmandeh.com/post/kemenag-pessel-gelar-raker-tahun-2022-di-pandan-view-kawasan-mandeh',
                'session_id' => 'Nz6qippgUHtU8jVH15jXlLyCiNAEJ3DPO6zMHISs',
                'user_id' => NULL,
                'ip' => '35.203.251.13',
            'agent' => 'Mozilla/5.0 (compatible; XML sitemap generator; octopus.do) Gecko Octopus/1.0',
                'created_at' => '2023-07-13 10:41:08',
                'updated_at' => '2023-07-13 10:41:08',
            ),
            44 => 
            array (
                'id' => 45,
                'post_id' => 5,
                'slug' => 'perbedaan-hotel-bungalow-resort-cottage-dan-villa',
                'url' => 'https://pandanviewmandeh.com/post/perbedaan-hotel-bungalow-resort-cottage-dan-villa',
                'session_id' => 'B4H53bk8zlfp6QDUNEO5HWWmNeXwZ5MXcvP1cjze',
                'user_id' => NULL,
                'ip' => '35.203.251.13',
            'agent' => 'Mozilla/5.0 (compatible; XML sitemap generator; octopus.do) Gecko Octopus/1.0',
                'created_at' => '2023-07-13 10:41:09',
                'updated_at' => '2023-07-13 10:41:09',
            ),
            45 => 
            array (
                'id' => 46,
                'post_id' => 10,
                'slug' => 'misteri-menyelubungi-rumah-gadang-mande-rubiyah-keajaiban-arsitektur-dengan-kisah-yang-tersimpan',
                'url' => 'https://pandanviewmandeh.com/post/misteri-menyelubungi-rumah-gadang-mande-rubiyah-keajaiban-arsitektur-dengan-kisah-yang-tersimpan',
                'session_id' => 'ICyDFcoIc1VbQksqJiOfhWFvscuRsZBP68jpAoIb',
                'user_id' => NULL,
                'ip' => '35.203.251.13',
            'agent' => 'Mozilla/5.0 (compatible; XML sitemap generator; octopus.do) Gecko Octopus/1.0',
                'created_at' => '2023-07-13 10:41:10',
                'updated_at' => '2023-07-13 10:41:10',
            ),
            46 => 
            array (
                'id' => 47,
                'post_id' => 9,
                'slug' => 'keindahan-lautan-yang-menakjubkan-eksplorasi-gugusan-mandeh-di-sumatera-barat',
                'url' => 'https://pandanviewmandeh.com/post/keindahan-lautan-yang-menakjubkan-eksplorasi-gugusan-mandeh-di-sumatera-barat',
                'session_id' => 'Rr7KH0ngQhi9q6uMVDdYtTw7U7Dt9d1MtKiHb1zi',
                'user_id' => NULL,
                'ip' => '35.203.251.13',
            'agent' => 'Mozilla/5.0 (compatible; XML sitemap generator; octopus.do) Gecko Octopus/1.0',
                'created_at' => '2023-07-13 10:41:10',
                'updated_at' => '2023-07-13 10:41:10',
            ),
            47 => 
            array (
                'id' => 48,
                'post_id' => 8,
                'slug' => 'menguasai-sales-dan-marketing-di-industri-pariwisata-strategi-sukses-untuk-menggaet-pengunjung-dan-meningkatkan-penjualan',
                'url' => 'https://pandanviewmandeh.com/post/menguasai-sales-dan-marketing-di-industri-pariwisata-strategi-sukses-untuk-menggaet-pengunjung-dan-meningkatkan-penjualan',
                'session_id' => 'hm2lbIaj8zhIyGVcgGpMGzUExbMCDIIPiGdE6oJF',
                'user_id' => NULL,
                'ip' => '35.203.251.13',
            'agent' => 'Mozilla/5.0 (compatible; XML sitemap generator; octopus.do) Gecko Octopus/1.0',
                'created_at' => '2023-07-13 10:41:11',
                'updated_at' => '2023-07-13 10:41:11',
            ),
            48 => 
            array (
                'id' => 49,
                'post_id' => 7,
                'slug' => 'menjelajahi-dunia-melalui-pariwisata-merayakan-keajaiban-alam-dan-budaya',
                'url' => 'https://pandanviewmandeh.com/post/menjelajahi-dunia-melalui-pariwisata-merayakan-keajaiban-alam-dan-budaya',
                'session_id' => 'JkjctAEad4CRGddt2jx1P1IRKxIENuBFuabgtJl7',
                'user_id' => NULL,
                'ip' => '35.203.251.13',
            'agent' => 'Mozilla/5.0 (compatible; XML sitemap generator; octopus.do) Gecko Octopus/1.0',
                'created_at' => '2023-07-13 10:41:11',
                'updated_at' => '2023-07-13 10:41:11',
            ),
            49 => 
            array (
                'id' => 50,
                'post_id' => 6,
                'slug' => 'pandan-view-mandeh-keindahan-puncak-mandeh-yang-menakjubkan',
                'url' => 'https://pandanviewmandeh.com/post/pandan-view-mandeh-keindahan-puncak-mandeh-yang-menakjubkan',
                'session_id' => 'XyqX1OU3mrb4knMRxx4HLgRAlgpqOrRpUAkcYX3R',
                'user_id' => NULL,
                'ip' => '35.203.251.13',
            'agent' => 'Mozilla/5.0 (compatible; XML sitemap generator; octopus.do) Gecko Octopus/1.0',
                'created_at' => '2023-07-13 10:41:19',
                'updated_at' => '2023-07-13 10:41:19',
            ),
            50 => 
            array (
                'id' => 51,
                'post_id' => 10,
                'slug' => 'misteri-menyelubungi-rumah-gadang-mande-rubiyah-keajaiban-arsitektur-dengan-kisah-yang-tersimpan',
                'url' => 'https://pandanviewmandeh.com/post/misteri-menyelubungi-rumah-gadang-mande-rubiyah-keajaiban-arsitektur-dengan-kisah-yang-tersimpan',
                'session_id' => 'l6zAzVuOxTYBmZCejK3VqHFzsrg1TwxTX9AMcaeC',
                'user_id' => NULL,
                'ip' => '223.255.227.25',
            'agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36',
                'created_at' => '2023-07-13 15:28:32',
                'updated_at' => '2023-07-13 15:28:32',
            ),
            51 => 
            array (
                'id' => 52,
                'post_id' => 10,
                'slug' => 'misteri-menyelubungi-rumah-gadang-mande-rubiyah-keajaiban-arsitektur-dengan-kisah-yang-tersimpan',
                'url' => 'https://pandanviewmandeh.com/post/misteri-menyelubungi-rumah-gadang-mande-rubiyah-keajaiban-arsitektur-dengan-kisah-yang-tersimpan',
                'session_id' => 'T5qmu6Yw3hBtlwjkqTX3dq33YDWTYJhaaKIth8yN',
                'user_id' => 1,
                'ip' => '223.255.227.25',
            'agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36',
                'created_at' => '2023-07-13 16:25:46',
                'updated_at' => '2023-07-13 16:25:46',
            ),
            52 => 
            array (
                'id' => 53,
                'post_id' => 6,
                'slug' => 'pandan-view-mandeh-keindahan-puncak-mandeh-yang-menakjubkan',
                'url' => 'https://pandanviewmandeh.com/post/pandan-view-mandeh-keindahan-puncak-mandeh-yang-menakjubkan',
                'session_id' => 'WpEd2vvNTDU6RNTIVdU0Ew1T3vWEl7YoIBE8JwIR',
                'user_id' => 1,
                'ip' => '223.255.227.25',
            'agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36',
                'created_at' => '2023-07-13 17:43:43',
                'updated_at' => '2023-07-13 17:43:43',
            ),
            53 => 
            array (
                'id' => 54,
                'post_id' => 7,
                'slug' => 'menjelajahi-dunia-melalui-pariwisata-merayakan-keajaiban-alam-dan-budaya',
                'url' => 'http://pandanviewmandeh.com/post/menjelajahi-dunia-melalui-pariwisata-merayakan-keajaiban-alam-dan-budaya',
                'session_id' => 'GcrMCHpLxs8b2PWkM5BCPdYVzEvOjik0odrcLme0',
                'user_id' => NULL,
                'ip' => '66.249.79.6',
            'agent' => 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
                'created_at' => '2023-07-14 12:35:30',
                'updated_at' => '2023-07-14 12:35:30',
            ),
            54 => 
            array (
                'id' => 55,
                'post_id' => 10,
                'slug' => 'misteri-menyelubungi-rumah-gadang-mande-rubiyah-keajaiban-arsitektur-dengan-kisah-yang-tersimpan',
                'url' => 'https://pandanviewmandeh.com/post/misteri-menyelubungi-rumah-gadang-mande-rubiyah-keajaiban-arsitektur-dengan-kisah-yang-tersimpan',
                'session_id' => 'AvsWzR7iQW5AwNCf4kk1DXq08fLsIqHJXv6m8Ey4',
                'user_id' => NULL,
                'ip' => '66.249.71.67',
            'agent' => 'Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.179 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
                'created_at' => '2023-07-14 20:15:14',
                'updated_at' => '2023-07-14 20:15:14',
            ),
            55 => 
            array (
                'id' => 56,
                'post_id' => 9,
                'slug' => 'keindahan-lautan-yang-menakjubkan-eksplorasi-gugusan-mandeh-di-sumatera-barat',
                'url' => 'https://pandanviewmandeh.com/post/keindahan-lautan-yang-menakjubkan-eksplorasi-gugusan-mandeh-di-sumatera-barat',
                'session_id' => 'ri8HjsHcReEk1j9cudUhwd6ZGbe52AODfd1WGDt4',
                'user_id' => NULL,
                'ip' => '66.249.71.67',
                'agent' => 'Mediapartners-Google',
                'created_at' => '2023-07-15 17:31:27',
                'updated_at' => '2023-07-15 17:31:27',
            ),
            56 => 
            array (
                'id' => 57,
                'post_id' => 8,
                'slug' => 'menguasai-sales-dan-marketing-di-industri-pariwisata-strategi-sukses-untuk-menggaet-pengunjung-dan-meningkatkan-penjualan',
                'url' => 'https://pandanviewmandeh.com/post/menguasai-sales-dan-marketing-di-industri-pariwisata-strategi-sukses-untuk-menggaet-pengunjung-dan-meningkatkan-penjualan',
                'session_id' => 'cCl5g4iqvcTPLLF38bgPJquFaIlPh44RyYLUnxl8',
                'user_id' => NULL,
                'ip' => '66.249.79.12',
                'agent' => 'Mediapartners-Google',
                'created_at' => '2023-07-15 17:31:33',
                'updated_at' => '2023-07-15 17:31:33',
            ),
            57 => 
            array (
                'id' => 58,
                'post_id' => 7,
                'slug' => 'menjelajahi-dunia-melalui-pariwisata-merayakan-keajaiban-alam-dan-budaya',
                'url' => 'https://pandanviewmandeh.com/post/menjelajahi-dunia-melalui-pariwisata-merayakan-keajaiban-alam-dan-budaya',
                'session_id' => '0c8dxZIm7S1zwjPPgMTI9T8zeLeWnAK2nJZebtwy',
                'user_id' => NULL,
                'ip' => '66.249.71.67',
                'agent' => 'Mediapartners-Google',
                'created_at' => '2023-07-15 17:31:38',
                'updated_at' => '2023-07-15 17:31:38',
            ),
            58 => 
            array (
                'id' => 59,
                'post_id' => 10,
                'slug' => 'misteri-menyelubungi-rumah-gadang-mande-rubiyah-keajaiban-arsitektur-dengan-kisah-yang-tersimpan',
                'url' => 'https://pandanviewmandeh.com/post/misteri-menyelubungi-rumah-gadang-mande-rubiyah-keajaiban-arsitektur-dengan-kisah-yang-tersimpan',
                'session_id' => 'XSImH9JnXD7sQouYXsvCOANAoVot0Cdpnch8B2GR',
                'user_id' => NULL,
                'ip' => '66.249.79.12',
                'agent' => 'Mediapartners-Google',
                'created_at' => '2023-07-15 17:31:45',
                'updated_at' => '2023-07-15 17:31:45',
            ),
            59 => 
            array (
                'id' => 60,
                'post_id' => 9,
                'slug' => 'keindahan-lautan-yang-menakjubkan-eksplorasi-gugusan-mandeh-di-sumatera-barat',
                'url' => 'http://www.pandanviewmandeh.com/post/keindahan-lautan-yang-menakjubkan-eksplorasi-gugusan-mandeh-di-sumatera-barat',
                'session_id' => 'cEXnWZMxUqltnQ8RrIh4Iirs5VN4m1sDbMKCwwZp',
                'user_id' => NULL,
                'ip' => '66.249.71.165',
                'agent' => 'Mediapartners-Google',
                'created_at' => '2023-07-15 17:33:11',
                'updated_at' => '2023-07-15 17:33:11',
            ),
            60 => 
            array (
                'id' => 61,
                'post_id' => 8,
                'slug' => 'menguasai-sales-dan-marketing-di-industri-pariwisata-strategi-sukses-untuk-menggaet-pengunjung-dan-meningkatkan-penjualan',
                'url' => 'http://www.pandanviewmandeh.com/post/menguasai-sales-dan-marketing-di-industri-pariwisata-strategi-sukses-untuk-menggaet-pengunjung-dan-meningkatkan-penjualan',
                'session_id' => 'hg2Bz9lf357fw4bJfjWpRZrAYs053KVpvJXxcSUm',
                'user_id' => NULL,
                'ip' => '66.249.71.164',
                'agent' => 'Mediapartners-Google',
                'created_at' => '2023-07-15 17:33:17',
                'updated_at' => '2023-07-15 17:33:17',
            ),
            61 => 
            array (
                'id' => 62,
                'post_id' => 7,
                'slug' => 'menjelajahi-dunia-melalui-pariwisata-merayakan-keajaiban-alam-dan-budaya',
                'url' => 'http://www.pandanviewmandeh.com/post/menjelajahi-dunia-melalui-pariwisata-merayakan-keajaiban-alam-dan-budaya',
                'session_id' => 'ptJyk5wmEmG68uRenU415FESCIUUfBsUrIZCousf',
                'user_id' => NULL,
                'ip' => '66.249.71.164',
                'agent' => 'Mediapartners-Google',
                'created_at' => '2023-07-15 17:33:22',
                'updated_at' => '2023-07-15 17:33:22',
            ),
            62 => 
            array (
                'id' => 63,
                'post_id' => 10,
                'slug' => 'misteri-menyelubungi-rumah-gadang-mande-rubiyah-keajaiban-arsitektur-dengan-kisah-yang-tersimpan',
                'url' => 'http://www.pandanviewmandeh.com/post/misteri-menyelubungi-rumah-gadang-mande-rubiyah-keajaiban-arsitektur-dengan-kisah-yang-tersimpan',
                'session_id' => 'BPORgsuElJflIcHWnHxqnJKfnLwSpOYzl2XdAvuc',
                'user_id' => NULL,
                'ip' => '66.249.71.164',
                'agent' => 'Mediapartners-Google',
                'created_at' => '2023-07-15 17:33:28',
                'updated_at' => '2023-07-15 17:33:28',
            ),
            63 => 
            array (
                'id' => 64,
                'post_id' => 6,
                'slug' => 'pandan-view-mandeh-keindahan-puncak-mandeh-yang-menakjubkan',
                'url' => 'http://www.pandanviewmandeh.com/post/pandan-view-mandeh-keindahan-puncak-mandeh-yang-menakjubkan',
                'session_id' => 'c1INVynWDf7EJHFQq3TZFpYxYkJB3CgD4eTvQSS4',
                'user_id' => NULL,
                'ip' => '66.249.71.164',
                'agent' => 'Mediapartners-Google',
                'created_at' => '2023-07-15 17:33:32',
                'updated_at' => '2023-07-15 17:33:32',
            ),
            64 => 
            array (
                'id' => 65,
                'post_id' => 4,
                'slug' => 'kemenag-pessel-gelar-raker-tahun-2022-di-pandan-view-kawasan-mandeh',
                'url' => 'https://pandanviewmandeh.com/post/kemenag-pessel-gelar-raker-tahun-2022-di-pandan-view-kawasan-mandeh',
                'session_id' => 'gK8McZD9u8Yfl2ZK5MueRaK8hVKzGTjvRzb8eUgW',
                'user_id' => NULL,
                'ip' => '66.249.79.12',
                'agent' => 'Mediapartners-Google',
                'created_at' => '2023-07-15 17:35:13',
                'updated_at' => '2023-07-15 17:35:13',
            ),
            65 => 
            array (
                'id' => 66,
                'post_id' => 1,
                'slug' => 'menikmati-lezatnya-snack-di-pandan-view-mandeh',
                'url' => 'https://pandanviewmandeh.com/post/menikmati-lezatnya-snack-di-pandan-view-mandeh',
                'session_id' => 'Q6W5NxyXV2wbKG2bzgZ8L1V5D0H4qMfl0QBNUjoY',
                'user_id' => NULL,
                'ip' => '66.249.79.12',
                'agent' => 'Mediapartners-Google',
                'created_at' => '2023-07-15 17:35:17',
                'updated_at' => '2023-07-15 17:35:17',
            ),
            66 => 
            array (
                'id' => 67,
                'post_id' => 3,
                'slug' => 'pandan-view-mandeh-resort',
                'url' => 'https://pandanviewmandeh.com/post/pandan-view-mandeh-resort',
                'session_id' => 'wG7J4S3yK73hL5ke2Dnq9GpXdXiB5ivabPwSWu1i',
                'user_id' => NULL,
                'ip' => '66.249.79.12',
                'agent' => 'Mediapartners-Google',
                'created_at' => '2023-07-15 17:35:26',
                'updated_at' => '2023-07-15 17:35:26',
            ),
            67 => 
            array (
                'id' => 68,
                'post_id' => 2,
                'slug' => 'tips-traveling-di-sumatera-barat-menikmati-keindahan-alam-dan-budaya',
                'url' => 'https://pandanviewmandeh.com/post/tips-traveling-di-sumatera-barat-menikmati-keindahan-alam-dan-budaya',
                'session_id' => 'SDHvCsI3Bj35I6rDlqyy2RCQOoXRljOzzrtkFdAq',
                'user_id' => NULL,
                'ip' => '66.249.71.67',
                'agent' => 'Mediapartners-Google',
                'created_at' => '2023-07-15 17:35:35',
                'updated_at' => '2023-07-15 17:35:35',
            ),
            68 => 
            array (
                'id' => 69,
                'post_id' => 4,
                'slug' => 'kemenag-pessel-gelar-raker-tahun-2022-di-pandan-view-kawasan-mandeh',
                'url' => 'http://www.pandanviewmandeh.com/post/kemenag-pessel-gelar-raker-tahun-2022-di-pandan-view-kawasan-mandeh',
                'session_id' => '7FD4jJ0nZJmHhu4pQfikvJJw19ImopNdADbCEOYX',
                'user_id' => NULL,
                'ip' => '66.249.68.34',
                'agent' => 'Mediapartners-Google',
                'created_at' => '2023-07-15 17:37:21',
                'updated_at' => '2023-07-15 17:37:21',
            ),
            69 => 
            array (
                'id' => 70,
                'post_id' => 3,
                'slug' => 'pandan-view-mandeh-resort',
                'url' => 'http://www.pandanviewmandeh.com/post/pandan-view-mandeh-resort',
                'session_id' => 'Ow40htFlvC8En7KyxulGXFpwdsuaDKUav0Umkx22',
                'user_id' => NULL,
                'ip' => '66.249.71.164',
                'agent' => 'Mediapartners-Google',
                'created_at' => '2023-07-15 17:37:27',
                'updated_at' => '2023-07-15 17:37:27',
            ),
            70 => 
            array (
                'id' => 71,
                'post_id' => 5,
                'slug' => 'perbedaan-hotel-bungalow-resort-cottage-dan-villa',
                'url' => 'http://www.pandanviewmandeh.com/post/perbedaan-hotel-bungalow-resort-cottage-dan-villa',
                'session_id' => '4CvXTAR4632y9oNbmObKf6COe3lNSKkNc4B6ZySj',
                'user_id' => NULL,
                'ip' => '66.249.68.34',
                'agent' => 'Mediapartners-Google',
                'created_at' => '2023-07-15 17:37:31',
                'updated_at' => '2023-07-15 17:37:31',
            ),
            71 => 
            array (
                'id' => 72,
                'post_id' => 2,
                'slug' => 'tips-traveling-di-sumatera-barat-menikmati-keindahan-alam-dan-budaya',
                'url' => 'http://www.pandanviewmandeh.com/post/tips-traveling-di-sumatera-barat-menikmati-keindahan-alam-dan-budaya',
                'session_id' => 'PZLzNtNVDJWMsHZzFLr0uIhVOywAWE37Y30g6s6J',
                'user_id' => NULL,
                'ip' => '66.249.71.164',
                'agent' => 'Mediapartners-Google',
                'created_at' => '2023-07-15 17:37:35',
                'updated_at' => '2023-07-15 17:37:35',
            ),
            72 => 
            array (
                'id' => 73,
                'post_id' => 6,
                'slug' => 'pandan-view-mandeh-keindahan-puncak-mandeh-yang-menakjubkan',
                'url' => 'https://pandanviewmandeh.com/post/pandan-view-mandeh-keindahan-puncak-mandeh-yang-menakjubkan',
                'session_id' => 'ZqgW12xxjabm8ie7fAmR7Wy05ZfjZkXifvw2jaGy',
                'user_id' => NULL,
                'ip' => '66.249.71.67',
            'agent' => 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
                'created_at' => '2023-07-15 21:01:12',
                'updated_at' => '2023-07-15 21:01:12',
            ),
            73 => 
            array (
                'id' => 74,
                'post_id' => 9,
                'slug' => 'keindahan-lautan-yang-menakjubkan-eksplorasi-gugusan-mandeh-di-sumatera-barat',
                'url' => 'https://pandanviewmandeh.com/post/keindahan-lautan-yang-menakjubkan-eksplorasi-gugusan-mandeh-di-sumatera-barat',
                'session_id' => 'cvNZKu9Q43mq0dpmDypQErtmzxo8UXhmqXnGuT3z',
                'user_id' => NULL,
                'ip' => '66.249.79.12',
            'agent' => 'Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.179 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
                'created_at' => '2023-07-15 21:02:04',
                'updated_at' => '2023-07-15 21:02:04',
            ),
            74 => 
            array (
                'id' => 75,
                'post_id' => 8,
                'slug' => 'menguasai-sales-dan-marketing-di-industri-pariwisata-strategi-sukses-untuk-menggaet-pengunjung-dan-meningkatkan-penjualan',
                'url' => 'https://pandanviewmandeh.com/post/menguasai-sales-dan-marketing-di-industri-pariwisata-strategi-sukses-untuk-menggaet-pengunjung-dan-meningkatkan-penjualan',
                'session_id' => 'KfPr6jmPLZ9VFdTildroYZThLWKwewv5cZ6iH1wA',
                'user_id' => NULL,
                'ip' => '66.249.71.67',
            'agent' => 'Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.179 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
                'created_at' => '2023-07-15 21:02:57',
                'updated_at' => '2023-07-15 21:02:57',
            ),
            75 => 
            array (
                'id' => 76,
                'post_id' => 7,
                'slug' => 'menjelajahi-dunia-melalui-pariwisata-merayakan-keajaiban-alam-dan-budaya',
                'url' => 'https://pandanviewmandeh.com/post/menjelajahi-dunia-melalui-pariwisata-merayakan-keajaiban-alam-dan-budaya',
                'session_id' => 'YM3uFyxUWTrLcT1cMurdoZB4V0FPGoBZrEtYGDOf',
                'user_id' => NULL,
                'ip' => '66.249.79.12',
            'agent' => 'Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.179 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
                'created_at' => '2023-07-15 21:04:42',
                'updated_at' => '2023-07-15 21:04:42',
            ),
            76 => 
            array (
                'id' => 77,
                'post_id' => 10,
                'slug' => 'misteri-menyelubungi-rumah-gadang-mande-rubiyah-keajaiban-arsitektur-dengan-kisah-yang-tersimpan',
                'url' => 'https://pandanviewmandeh.com/post/misteri-menyelubungi-rumah-gadang-mande-rubiyah-keajaiban-arsitektur-dengan-kisah-yang-tersimpan',
                'session_id' => 'kDc6MQHCSmXXRKET0PBWlUkJFwGygxOq7wwmU8Aq',
                'user_id' => NULL,
                'ip' => '66.249.71.68',
            'agent' => 'Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.179 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
                'created_at' => '2023-07-15 21:05:34',
                'updated_at' => '2023-07-15 21:05:34',
            ),
            77 => 
            array (
                'id' => 78,
                'post_id' => 4,
                'slug' => 'kemenag-pessel-gelar-raker-tahun-2022-di-pandan-view-kawasan-mandeh',
                'url' => 'https://pandanviewmandeh.com/post/kemenag-pessel-gelar-raker-tahun-2022-di-pandan-view-kawasan-mandeh',
                'session_id' => 'tFxxew2IRR2OHC3g01x6aLPExkJhhcnGrzufLrqp',
                'user_id' => NULL,
                'ip' => '66.249.71.67',
            'agent' => 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
                'created_at' => '2023-07-15 21:07:53',
                'updated_at' => '2023-07-15 21:07:53',
            ),
            78 => 
            array (
                'id' => 79,
                'post_id' => 9,
                'slug' => 'keindahan-lautan-yang-menakjubkan-eksplorasi-gugusan-mandeh-di-sumatera-barat',
                'url' => 'https://pandanviewmandeh.com/post/keindahan-lautan-yang-menakjubkan-eksplorasi-gugusan-mandeh-di-sumatera-barat',
                'session_id' => 'ifBHutyEfqQWpQlWLhUYHv0OUerQ8cUWBd3WNJEw',
                'user_id' => NULL,
                'ip' => '66.249.79.13',
            'agent' => 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
                'created_at' => '2023-07-15 21:08:31',
                'updated_at' => '2023-07-15 21:08:31',
            ),
            79 => 
            array (
                'id' => 80,
                'post_id' => 5,
                'slug' => 'perbedaan-hotel-bungalow-resort-cottage-dan-villa',
                'url' => 'https://pandanviewmandeh.com/post/perbedaan-hotel-bungalow-resort-cottage-dan-villa',
                'session_id' => 'Dyp3bv0iL1FwAhdYxkgaNelnb6jx4idXYARiKRH4',
                'user_id' => NULL,
                'ip' => '66.249.79.12',
            'agent' => 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
                'created_at' => '2023-07-15 21:09:38',
                'updated_at' => '2023-07-15 21:09:38',
            ),
            80 => 
            array (
                'id' => 81,
                'post_id' => 3,
                'slug' => 'pandan-view-mandeh-resort',
                'url' => 'https://pandanviewmandeh.com/post/pandan-view-mandeh-resort',
                'session_id' => '0lYP50NkzqvRQ4WqbTO6Poq4rvJfAzpVBnnRdRaO',
                'user_id' => NULL,
                'ip' => '66.249.79.13',
            'agent' => 'Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.179 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
                'created_at' => '2023-07-15 21:11:23',
                'updated_at' => '2023-07-15 21:11:23',
            ),
            81 => 
            array (
                'id' => 82,
                'post_id' => 1,
                'slug' => 'menikmati-lezatnya-snack-di-pandan-view-mandeh',
                'url' => 'https://pandanviewmandeh.com/post/menikmati-lezatnya-snack-di-pandan-view-mandeh',
                'session_id' => 'HtpdnhwHrbcVh7VoifVIe54PZAaJq7mQo2X1yxw6',
                'user_id' => NULL,
                'ip' => '66.249.71.67',
            'agent' => 'Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.179 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
                'created_at' => '2023-07-15 21:11:40',
                'updated_at' => '2023-07-15 21:11:40',
            ),
            82 => 
            array (
                'id' => 83,
                'post_id' => 3,
                'slug' => 'pandan-view-mandeh-resort',
                'url' => 'https://pandanviewmandeh.com/post/pandan-view-mandeh-resort',
                'session_id' => 'Vo3Vu7LP8bieTmGwWTU3sdmOQ9EDvLsrzIGuw7gk',
                'user_id' => NULL,
                'ip' => '66.249.71.67',
            'agent' => 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
                'created_at' => '2023-07-15 21:11:58',
                'updated_at' => '2023-07-15 21:11:58',
            ),
            83 => 
            array (
                'id' => 84,
                'post_id' => 1,
                'slug' => 'menikmati-lezatnya-snack-di-pandan-view-mandeh',
                'url' => 'https://pandanviewmandeh.com/post/menikmati-lezatnya-snack-di-pandan-view-mandeh',
                'session_id' => 'ypduvongTCw4JxcYemgb1w6BeuB4Wp6UZJ9bWEvV',
                'user_id' => NULL,
                'ip' => '66.249.79.14',
            'agent' => 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
                'created_at' => '2023-07-15 21:12:16',
                'updated_at' => '2023-07-15 21:12:16',
            ),
            84 => 
            array (
                'id' => 85,
                'post_id' => 10,
                'slug' => 'misteri-menyelubungi-rumah-gadang-mande-rubiyah-keajaiban-arsitektur-dengan-kisah-yang-tersimpan',
                'url' => 'https://pandanviewmandeh.com/post/misteri-menyelubungi-rumah-gadang-mande-rubiyah-keajaiban-arsitektur-dengan-kisah-yang-tersimpan',
                'session_id' => 'ghz3JxIgV1WBYGSVRP9IJiiG6s3i5NalEMbUS4Ko',
                'user_id' => NULL,
                'ip' => '66.249.71.69',
            'agent' => 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
                'created_at' => '2023-07-17 18:18:26',
                'updated_at' => '2023-07-17 18:18:26',
            ),
            85 => 
            array (
                'id' => 86,
                'post_id' => 9,
                'slug' => 'keindahan-lautan-yang-menakjubkan-eksplorasi-gugusan-mandeh-di-sumatera-barat',
                'url' => 'http://pandanviewmandeh.com/post/keindahan-lautan-yang-menakjubkan-eksplorasi-gugusan-mandeh-di-sumatera-barat',
                'session_id' => 'JXwPLvVPLFPgTcvW9rdjo5nKMFjUZVOG6zp7RGxj',
                'user_id' => NULL,
                'ip' => '54.36.149.249',
            'agent' => 'Mozilla/5.0 (compatible; AhrefsSiteAudit/6.1; +http://ahrefs.com/robot/site-audit)',
                'created_at' => '2023-07-17 21:04:47',
                'updated_at' => '2023-07-17 21:04:47',
            ),
            86 => 
            array (
                'id' => 87,
                'post_id' => 10,
                'slug' => 'misteri-menyelubungi-rumah-gadang-mande-rubiyah-keajaiban-arsitektur-dengan-kisah-yang-tersimpan',
                'url' => 'http://pandanviewmandeh.com/post/misteri-menyelubungi-rumah-gadang-mande-rubiyah-keajaiban-arsitektur-dengan-kisah-yang-tersimpan',
                'session_id' => 'euumt70WdKhly6WdOceXhwNCvrtIf2jNIsTVriHv',
                'user_id' => NULL,
                'ip' => '54.36.149.242',
            'agent' => 'Mozilla/5.0 (compatible; AhrefsSiteAudit/6.1; +http://ahrefs.com/robot/site-audit)',
                'created_at' => '2023-07-17 21:04:54',
                'updated_at' => '2023-07-17 21:04:54',
            ),
            87 => 
            array (
                'id' => 88,
                'post_id' => 3,
                'slug' => 'pandan-view-mandeh-resort',
                'url' => 'http://pandanviewmandeh.com/post/pandan-view-mandeh-resort',
                'session_id' => 'RlzOC4Zi7btunoGjjGtI3MZuJwCPZX3aotWKstfA',
                'user_id' => NULL,
                'ip' => '54.36.149.244',
            'agent' => 'Mozilla/5.0 (compatible; AhrefsSiteAudit/6.1; +http://ahrefs.com/robot/site-audit)',
                'created_at' => '2023-07-17 21:05:01',
                'updated_at' => '2023-07-17 21:05:01',
            ),
            88 => 
            array (
                'id' => 89,
                'post_id' => 2,
                'slug' => 'tips-traveling-di-sumatera-barat-menikmati-keindahan-alam-dan-budaya',
                'url' => 'http://pandanviewmandeh.com/post/tips-traveling-di-sumatera-barat-menikmati-keindahan-alam-dan-budaya',
                'session_id' => 'eu38BA9VkLcjwT0Mxzntx3G0qPcrocsRy7PzHnNq',
                'user_id' => NULL,
                'ip' => '54.36.149.242',
            'agent' => 'Mozilla/5.0 (compatible; AhrefsSiteAudit/6.1; +http://ahrefs.com/robot/site-audit)',
                'created_at' => '2023-07-17 21:05:14',
                'updated_at' => '2023-07-17 21:05:14',
            ),
            89 => 
            array (
                'id' => 90,
                'post_id' => 8,
                'slug' => 'menguasai-sales-dan-marketing-di-industri-pariwisata-strategi-sukses-untuk-menggaet-pengunjung-dan-meningkatkan-penjualan',
                'url' => 'http://pandanviewmandeh.com/post/menguasai-sales-dan-marketing-di-industri-pariwisata-strategi-sukses-untuk-menggaet-pengunjung-dan-meningkatkan-penjualan',
                'session_id' => 'A3ZmfOdH1nMC1H7b5W66kpoDaFHtT2uyp0aP8cpN',
                'user_id' => NULL,
                'ip' => '54.36.149.247',
            'agent' => 'Mozilla/5.0 (compatible; AhrefsSiteAudit/6.1; +http://ahrefs.com/robot/site-audit)',
                'created_at' => '2023-07-17 21:05:31',
                'updated_at' => '2023-07-17 21:05:31',
            ),
            90 => 
            array (
                'id' => 91,
                'post_id' => 6,
                'slug' => 'pandan-view-mandeh-keindahan-puncak-mandeh-yang-menakjubkan',
                'url' => 'http://pandanviewmandeh.com/post/pandan-view-mandeh-keindahan-puncak-mandeh-yang-menakjubkan',
                'session_id' => 'Ph7FX92QsFbxeT7ORDO5o6MslKfHNG3oNisiYsgQ',
                'user_id' => NULL,
                'ip' => '54.36.149.249',
            'agent' => 'Mozilla/5.0 (compatible; AhrefsSiteAudit/6.1; +http://ahrefs.com/robot/site-audit)',
                'created_at' => '2023-07-17 21:05:38',
                'updated_at' => '2023-07-17 21:05:38',
            ),
            91 => 
            array (
                'id' => 92,
                'post_id' => 7,
                'slug' => 'menjelajahi-dunia-melalui-pariwisata-merayakan-keajaiban-alam-dan-budaya',
                'url' => 'http://pandanviewmandeh.com/post/menjelajahi-dunia-melalui-pariwisata-merayakan-keajaiban-alam-dan-budaya',
                'session_id' => '88xT2VHlHeEvNRzbj1tMuha2tmTTiUSpjif7YmtV',
                'user_id' => NULL,
                'ip' => '54.36.149.247',
            'agent' => 'Mozilla/5.0 (compatible; AhrefsSiteAudit/6.1; +http://ahrefs.com/robot/site-audit)',
                'created_at' => '2023-07-17 21:05:49',
                'updated_at' => '2023-07-17 21:05:49',
            ),
            92 => 
            array (
                'id' => 93,
                'post_id' => 4,
                'slug' => 'kemenag-pessel-gelar-raker-tahun-2022-di-pandan-view-kawasan-mandeh',
                'url' => 'http://pandanviewmandeh.com/post/kemenag-pessel-gelar-raker-tahun-2022-di-pandan-view-kawasan-mandeh',
                'session_id' => '6fbcq5iJxuJEKd6SVLoytDFnJ3masfzDwlkhmbGj',
                'user_id' => NULL,
                'ip' => '54.36.149.240',
            'agent' => 'Mozilla/5.0 (compatible; AhrefsSiteAudit/6.1; +http://ahrefs.com/robot/site-audit)',
                'created_at' => '2023-07-17 21:05:52',
                'updated_at' => '2023-07-17 21:05:52',
            ),
            93 => 
            array (
                'id' => 94,
                'post_id' => 5,
                'slug' => 'perbedaan-hotel-bungalow-resort-cottage-dan-villa',
                'url' => 'http://pandanviewmandeh.com/post/perbedaan-hotel-bungalow-resort-cottage-dan-villa',
                'session_id' => 'OZhZ6OsO8DzEejNpmXoqIDebymuOZMgBPHk6U4oI',
                'user_id' => NULL,
                'ip' => '54.36.149.243',
            'agent' => 'Mozilla/5.0 (compatible; AhrefsSiteAudit/6.1; +http://ahrefs.com/robot/site-audit)',
                'created_at' => '2023-07-17 21:05:59',
                'updated_at' => '2023-07-17 21:05:59',
            ),
            94 => 
            array (
                'id' => 95,
                'post_id' => 1,
                'slug' => 'menikmati-lezatnya-snack-di-pandan-view-mandeh',
                'url' => 'http://pandanviewmandeh.com/post/menikmati-lezatnya-snack-di-pandan-view-mandeh',
                'session_id' => 'wwaU32tg81EhWdgtJVI6tYXaDcP0SIua57ORLaRf',
                'user_id' => NULL,
                'ip' => '54.36.149.248',
            'agent' => 'Mozilla/5.0 (compatible; AhrefsSiteAudit/6.1; +http://ahrefs.com/robot/site-audit)',
                'created_at' => '2023-07-17 21:06:05',
                'updated_at' => '2023-07-17 21:06:05',
            ),
            95 => 
            array (
                'id' => 96,
                'post_id' => 9,
                'slug' => 'keindahan-lautan-yang-menakjubkan-eksplorasi-gugusan-mandeh-di-sumatera-barat',
                'url' => 'https://pandanviewmandeh.com/post/keindahan-lautan-yang-menakjubkan-eksplorasi-gugusan-mandeh-di-sumatera-barat',
                'session_id' => 'PeMA40xYBmbPgkpMY6a8YluixMa3AZUfrpNlmAGB',
                'user_id' => NULL,
                'ip' => '54.36.149.240',
            'agent' => 'Mozilla/5.0 (compatible; AhrefsSiteAudit/6.1; +http://ahrefs.com/robot/site-audit)',
                'created_at' => '2023-07-17 21:08:29',
                'updated_at' => '2023-07-17 21:08:29',
            ),
            96 => 
            array (
                'id' => 97,
                'post_id' => 8,
                'slug' => 'menguasai-sales-dan-marketing-di-industri-pariwisata-strategi-sukses-untuk-menggaet-pengunjung-dan-meningkatkan-penjualan',
                'url' => 'https://pandanviewmandeh.com/post/menguasai-sales-dan-marketing-di-industri-pariwisata-strategi-sukses-untuk-menggaet-pengunjung-dan-meningkatkan-penjualan',
                'session_id' => '6sp7wHUlFIISsg5hKwsMOzS0w9Llc9WNBgGEsmkz',
                'user_id' => NULL,
                'ip' => '54.36.149.240',
            'agent' => 'Mozilla/5.0 (compatible; AhrefsSiteAudit/6.1; +http://ahrefs.com/robot/site-audit)',
                'created_at' => '2023-07-17 21:08:32',
                'updated_at' => '2023-07-17 21:08:32',
            ),
            97 => 
            array (
                'id' => 98,
                'post_id' => 6,
                'slug' => 'pandan-view-mandeh-keindahan-puncak-mandeh-yang-menakjubkan',
                'url' => 'https://pandanviewmandeh.com/post/pandan-view-mandeh-keindahan-puncak-mandeh-yang-menakjubkan',
                'session_id' => '62uDZBX79sv2rmiGsIa0tZ6X2HasZ5La55TSQd0k',
                'user_id' => NULL,
                'ip' => '54.36.149.246',
            'agent' => 'Mozilla/5.0 (compatible; AhrefsSiteAudit/6.1; +http://ahrefs.com/robot/site-audit)',
                'created_at' => '2023-07-17 21:09:10',
                'updated_at' => '2023-07-17 21:09:10',
            ),
            98 => 
            array (
                'id' => 99,
                'post_id' => 7,
                'slug' => 'menjelajahi-dunia-melalui-pariwisata-merayakan-keajaiban-alam-dan-budaya',
                'url' => 'https://pandanviewmandeh.com/post/menjelajahi-dunia-melalui-pariwisata-merayakan-keajaiban-alam-dan-budaya',
                'session_id' => 'DsZt9RLBfMwpw1fQvLPqNdAbFFb0hkpWBUTwrAQ6',
                'user_id' => NULL,
                'ip' => '54.36.149.248',
            'agent' => 'Mozilla/5.0 (compatible; AhrefsSiteAudit/6.1; +http://ahrefs.com/robot/site-audit)',
                'created_at' => '2023-07-17 21:09:33',
                'updated_at' => '2023-07-17 21:09:33',
            ),
            99 => 
            array (
                'id' => 100,
                'post_id' => 1,
                'slug' => 'menikmati-lezatnya-snack-di-pandan-view-mandeh',
                'url' => 'https://pandanviewmandeh.com/post/menikmati-lezatnya-snack-di-pandan-view-mandeh',
                'session_id' => 'JyViP9wD1C41HNHgzRG1rldezd5DpBfBHckz1pRq',
                'user_id' => NULL,
                'ip' => '54.36.149.242',
            'agent' => 'Mozilla/5.0 (compatible; AhrefsSiteAudit/6.1; +http://ahrefs.com/robot/site-audit)',
                'created_at' => '2023-07-17 21:10:25',
                'updated_at' => '2023-07-17 21:10:25',
            ),
            100 => 
            array (
                'id' => 101,
                'post_id' => 5,
                'slug' => 'perbedaan-hotel-bungalow-resort-cottage-dan-villa',
                'url' => 'https://pandanviewmandeh.com/post/perbedaan-hotel-bungalow-resort-cottage-dan-villa',
                'session_id' => 'rv5qLErhUKke4gN3vQbCrUQ882aihF0p4FSBtEEP',
                'user_id' => NULL,
                'ip' => '54.36.149.249',
            'agent' => 'Mozilla/5.0 (compatible; AhrefsSiteAudit/6.1; +http://ahrefs.com/robot/site-audit)',
                'created_at' => '2023-07-17 21:10:50',
                'updated_at' => '2023-07-17 21:10:50',
            ),
            101 => 
            array (
                'id' => 102,
                'post_id' => 4,
                'slug' => 'kemenag-pessel-gelar-raker-tahun-2022-di-pandan-view-kawasan-mandeh',
                'url' => 'https://pandanviewmandeh.com/post/kemenag-pessel-gelar-raker-tahun-2022-di-pandan-view-kawasan-mandeh',
                'session_id' => 'BFdE6lY3P5cXMgVMflGWGAXP0Iqx0stLabvOLn7m',
                'user_id' => NULL,
                'ip' => '54.36.149.245',
            'agent' => 'Mozilla/5.0 (compatible; AhrefsSiteAudit/6.1; +http://ahrefs.com/robot/site-audit)',
                'created_at' => '2023-07-17 21:11:04',
                'updated_at' => '2023-07-17 21:11:04',
            ),
            102 => 
            array (
                'id' => 103,
                'post_id' => 3,
                'slug' => 'pandan-view-mandeh-resort',
                'url' => 'https://pandanviewmandeh.com/post/pandan-view-mandeh-resort',
                'session_id' => '9PhwPdzQRJrQb2o1lXkG5CZQTduzJsKZVoiCmAxZ',
                'user_id' => NULL,
                'ip' => '54.36.149.240',
            'agent' => 'Mozilla/5.0 (compatible; AhrefsSiteAudit/6.1; +http://ahrefs.com/robot/site-audit)',
                'created_at' => '2023-07-17 21:11:11',
                'updated_at' => '2023-07-17 21:11:11',
            ),
            103 => 
            array (
                'id' => 104,
                'post_id' => 2,
                'slug' => 'tips-traveling-di-sumatera-barat-menikmati-keindahan-alam-dan-budaya',
                'url' => 'https://pandanviewmandeh.com/post/tips-traveling-di-sumatera-barat-menikmati-keindahan-alam-dan-budaya',
                'session_id' => 'shnpXBrr3FFfwjJKamoxI5hdoPg9ZTblnnAZH4MH',
                'user_id' => NULL,
                'ip' => '54.36.149.245',
            'agent' => 'Mozilla/5.0 (compatible; AhrefsSiteAudit/6.1; +http://ahrefs.com/robot/site-audit)',
                'created_at' => '2023-07-17 21:11:15',
                'updated_at' => '2023-07-17 21:11:15',
            ),
        ));
        
        
    }
}