<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ReservationsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('reservations')->delete();
        
        \DB::table('reservations')->insert(array (
            0 => 
            array (
                'id_reservation' => 1,
                'created_at' => '2023-07-17 15:42:51',
                'updated_at' => '2023-07-19 20:45:16',
                'deleted_at' => '2023-07-19 20:45:16',
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-13',
                'customer_name' => 'SEPTA APRIYENTI',
                'customer_phone' => NULL,
                'total_guest' => 5,
                'fix_price' => NULL,
                'down_payment' => 500000,
                'notes' => '3 EXTRACASH ANAK 50K',
            ),
            1 => 
            array (
                'id_reservation' => 2,
                'created_at' => '2023-07-17 15:43:34',
                'updated_at' => '2023-07-17 15:43:34',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-13',
                'customer_name' => 'YUDHA AYU KURNIANTY',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 850000,
                'notes' => 'EXTRABED/EXTRACASH MENYUSUL',
            ),
            2 => 
            array (
                'id_reservation' => 3,
                'created_at' => '2023-07-17 15:44:13',
                'updated_at' => '2023-07-17 15:44:13',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-13',
                'customer_name' => 'RONI MULYADI',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 2000000,
                'notes' => NULL,
            ),
            3 => 
            array (
                'id_reservation' => 4,
                'created_at' => '2023-07-17 15:44:51',
                'updated_at' => '2023-07-17 15:44:51',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-13',
                'customer_name' => 'AYA',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 1100000,
                'notes' => NULL,
            ),
            4 => 
            array (
                'id_reservation' => 5,
                'created_at' => '2023-07-17 15:47:29',
                'updated_at' => '2023-07-17 15:47:29',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-13',
                'customer_name' => 'DINAS PERHUBUNGAN',
                'customer_phone' => NULL,
                'total_guest' => 30,
                'fix_price' => NULL,
                'down_payment' => NULL,
                'notes' => NULL,
            ),
            5 => 
            array (
                'id_reservation' => 6,
                'created_at' => '2023-07-17 20:56:16',
                'updated_at' => '2023-07-17 20:56:16',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-14',
                'customer_name' => 'NETI HERAWATI',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 700000,
                'notes' => '2 CASH ANAK 50K',
            ),
            6 => 
            array (
                'id_reservation' => 7,
                'created_at' => '2023-07-17 20:57:08',
                'updated_at' => '2023-07-17 20:57:08',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-14',
                'customer_name' => 'PAK ANTON',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 650000,
                'notes' => NULL,
            ),
            7 => 
            array (
                'id_reservation' => 8,
                'created_at' => '2023-07-17 20:58:40',
                'updated_at' => '2023-07-17 20:58:40',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-15',
                'customer_name' => 'PAK DANI BCA',
                'customer_phone' => NULL,
                'total_guest' => 50,
                'fix_price' => NULL,
                'down_payment' => 11000000,
                'notes' => NULL,
            ),
            8 => 
            array (
                'id_reservation' => 9,
                'created_at' => '2023-07-17 20:59:37',
                'updated_at' => '2023-07-17 20:59:37',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-15',
                'customer_name' => 'NURUL MEDYA',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 1150000,
                'notes' => '3 ADDITIONAL CASH DEWASA',
            ),
            9 => 
            array (
                'id_reservation' => 10,
                'created_at' => '2023-07-17 21:00:35',
                'updated_at' => '2023-07-17 21:00:35',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-16',
                'customer_name' => 'SANDI DUTA PESONA',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 2000000,
                'notes' => NULL,
            ),
            10 => 
            array (
                'id_reservation' => 11,
                'created_at' => '2023-07-17 21:01:06',
                'updated_at' => '2023-07-17 21:01:06',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-16',
                'customer_name' => 'SRI AYU',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 1400000,
                'notes' => '2 EXTRABED+ 2 ADDITITIONAL CASH TANP BED',
            ),
            11 => 
            array (
                'id_reservation' => 12,
                'created_at' => '2023-07-17 21:01:46',
                'updated_at' => '2023-07-17 21:01:46',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-16',
                'customer_name' => 'JEF',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 850000,
                'notes' => 'EXTRABED/EXTRACASH MENYUSUL',
            ),
            12 => 
            array (
                'id_reservation' => 13,
                'created_at' => '2023-07-17 23:01:07',
                'updated_at' => '2023-07-17 23:01:07',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-17',
                'customer_name' => 'SANDI DUTA PESONA',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 0,
                'notes' => NULL,
            ),
            13 => 
            array (
                'id_reservation' => 14,
                'created_at' => '2023-07-17 23:01:51',
                'updated_at' => '2023-07-17 23:01:51',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-17',
                'customer_name' => 'UNI ELISDA NAZARUDDIN',
                'customer_phone' => NULL,
                'total_guest' => 35,
                'fix_price' => NULL,
                'down_payment' => 0,
                'notes' => 'MAKAN SIANG DAN PAKET KEPULAU',
            ),
            14 => 
            array (
                'id_reservation' => 15,
                'created_at' => '2023-07-17 23:02:22',
                'updated_at' => '2023-07-17 23:02:22',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-17',
                'customer_name' => 'ADI DUTA PESONA',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 0,
                'notes' => NULL,
            ),
            15 => 
            array (
                'id_reservation' => 16,
                'created_at' => '2023-07-17 23:03:05',
                'updated_at' => '2023-07-17 23:03:05',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-18',
            'customer_name' => 'SILVIA (BUK NUR)',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 1500000,
                'notes' => '4 EXTRABED',
            ),
            16 => 
            array (
                'id_reservation' => 17,
                'created_at' => '2023-07-17 23:03:45',
                'updated_at' => '2023-07-17 23:03:45',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-18',
                'customer_name' => 'PAK ANTON',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 0,
                'notes' => NULL,
            ),
            17 => 
            array (
                'id_reservation' => 18,
                'created_at' => '2023-07-17 23:04:03',
                'updated_at' => '2023-07-17 23:05:58',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-19',
                'customer_name' => 'TANIA ALPIANI',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 350000,
                'notes' => NULL,
            ),
            18 => 
            array (
                'id_reservation' => 19,
                'created_at' => '2023-07-17 23:07:40',
                'updated_at' => '2023-07-17 23:07:40',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-19',
            'customer_name' => 'ROLI SAPUTRA  (AN.MELLY)',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 400000,
                'notes' => NULL,
            ),
            19 => 
            array (
                'id_reservation' => 20,
                'created_at' => '2023-07-17 23:11:11',
                'updated_at' => '2023-07-17 23:11:11',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-20',
                'customer_name' => 'FARHAN  OKTA SDM MEKAR',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 0,
                'notes' => NULL,
            ),
            20 => 
            array (
                'id_reservation' => 21,
                'created_at' => '2023-07-17 23:11:35',
                'updated_at' => '2023-07-17 23:11:35',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-20',
                'customer_name' => 'ASNITA',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 350000,
                'notes' => NULL,
            ),
            21 => 
            array (
                'id_reservation' => 22,
                'created_at' => '2023-07-17 23:12:16',
                'updated_at' => '2023-07-17 23:12:16',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-21',
                'customer_name' => 'IKE ARDIANSIH',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 1500000,
                'notes' => '5 EXTRABED DISC 10%',
            ),
            22 => 
            array (
                'id_reservation' => 23,
                'created_at' => '2023-07-17 23:53:31',
                'updated_at' => '2023-07-19 20:45:20',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-12',
                'customer_name' => 'BUL HELLWIZA',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 350000,
                'notes' => NULL,
            ),
            23 => 
            array (
                'id_reservation' => 24,
                'created_at' => '2023-07-18 02:31:23',
                'updated_at' => '2023-07-18 02:31:23',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 8,
                'checkin_date' => '2023-08-02',
                'customer_name' => 'ACIAK',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 0,
                'notes' => NULL,
            ),
            24 => 
            array (
                'id_reservation' => 25,
                'created_at' => '2023-07-18 02:31:47',
                'updated_at' => '2023-07-18 02:31:47',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 8,
                'checkin_date' => '2023-08-03',
                'customer_name' => 'YOSI MAHDALENA',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 350000,
                'notes' => NULL,
            ),
            25 => 
            array (
                'id_reservation' => 26,
                'created_at' => '2023-07-18 02:32:23',
                'updated_at' => '2023-07-18 02:32:23',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 8,
                'checkin_date' => '2023-08-04',
                'customer_name' => 'DAVID KEUMALA HOLIDAY PDG',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 0,
                'notes' => NULL,
            ),
            26 => 
            array (
                'id_reservation' => 27,
                'created_at' => '2023-07-18 02:33:08',
                'updated_at' => '2023-07-18 02:33:08',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 8,
                'checkin_date' => '2023-08-04',
                'customer_name' => 'MAULIDA FATIHA TRAVEL',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 0,
                'notes' => NULL,
            ),
            27 => 
            array (
                'id_reservation' => 28,
                'created_at' => '2023-07-18 02:33:57',
                'updated_at' => '2023-07-18 02:33:57',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 8,
                'checkin_date' => '2023-08-06',
                'customer_name' => 'PUTRI ZELFITRI',
                'customer_phone' => NULL,
                'total_guest' => 100,
                'fix_price' => NULL,
                'down_payment' => 0,
                'notes' => 'ACARA GHATENG/ NGINAP',
            ),
            28 => 
            array (
                'id_reservation' => 29,
                'created_at' => '2023-07-18 02:35:09',
                'updated_at' => '2023-07-18 02:35:09',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 8,
                'checkin_date' => '2023-08-11',
                'customer_name' => 'BUK ELSI NOVIA SMA 2 BUKIT',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 8400000,
                'notes' => '40 ORG, 400/ORANG,MKN SIANG, DI COTTAGE 4 ORG, VILLA 6 ORG',
            ),
            29 => 
            array (
                'id_reservation' => 30,
                'created_at' => '2023-07-20 10:05:36',
                'updated_at' => '2023-07-20 10:05:36',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-01',
            'customer_name' => 'HERMAN (PAK MANCA)',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 400000,
                'notes' => NULL,
            ),
            30 => 
            array (
                'id_reservation' => 31,
                'created_at' => '2023-07-20 10:06:02',
                'updated_at' => '2023-07-20 10:06:02',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-01',
            'customer_name' => 'WINA AGENT (fitra ramadani)',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 1000000,
                'notes' => '1 EXTRABED + 2 CASH 50K',
            ),
            31 => 
            array (
                'id_reservation' => 32,
                'created_at' => '2023-07-20 10:06:35',
                'updated_at' => '2023-07-20 10:06:35',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-01',
                'customer_name' => 'MIDA LAMTIUR LESTARI',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 700000,
                'notes' => NULL,
            ),
            32 => 
            array (
                'id_reservation' => 33,
                'created_at' => '2023-07-20 10:07:01',
                'updated_at' => '2023-07-20 10:07:01',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-01',
                'customer_name' => 'PAK DIDI PDG',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 400000,
                'notes' => '1 EXTRABED + 1 CASH 50K',
            ),
            33 => 
            array (
                'id_reservation' => 34,
                'created_at' => '2023-07-20 10:07:31',
                'updated_at' => '2023-07-20 10:07:31',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-01',
                'customer_name' => 'YENNY BUKITTINGGI',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 350000,
                'notes' => NULL,
            ),
            34 => 
            array (
                'id_reservation' => 35,
                'created_at' => '2023-07-20 10:07:52',
                'updated_at' => '2023-07-20 10:07:52',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-01',
                'customer_name' => 'ROZALINDA',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 1000000,
                'notes' => NULL,
            ),
            35 => 
            array (
                'id_reservation' => 36,
                'created_at' => '2023-07-20 10:08:20',
                'updated_at' => '2023-07-20 10:08:20',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-01',
                'customer_name' => 'MUHAMMAD AZKA',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 850000,
                'notes' => NULL,
            ),
            36 => 
            array (
                'id_reservation' => 37,
                'created_at' => '2023-07-20 10:08:46',
                'updated_at' => '2023-07-20 10:08:46',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-01',
                'customer_name' => 'RIKI OKTAVIA',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 1300000,
                'notes' => NULL,
            ),
            37 => 
            array (
                'id_reservation' => 38,
                'created_at' => '2023-07-20 10:09:09',
                'updated_at' => '2023-07-20 10:09:27',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-01',
                'customer_name' => 'ZUL HAM',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 400000,
                'notes' => NULL,
            ),
            38 => 
            array (
                'id_reservation' => 39,
                'created_at' => '2023-07-20 10:10:07',
                'updated_at' => '2023-07-20 10:10:07',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-01',
            'customer_name' => 'BUYA SUSANTO(ABRALNANDA)',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 0,
                'notes' => NULL,
            ),
            39 => 
            array (
                'id_reservation' => 40,
                'created_at' => '2023-07-20 10:10:41',
                'updated_at' => '2023-07-20 10:10:41',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-01',
            'customer_name' => 'BUYA SUSANTO(YUFRZAL PDG)',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 500000,
                'notes' => NULL,
            ),
            40 => 
            array (
                'id_reservation' => 41,
                'created_at' => '2023-07-20 10:15:31',
                'updated_at' => '2023-07-20 10:16:03',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-02',
                'customer_name' => 'AULIA SAFITRI',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 400000,
                'notes' => NULL,
            ),
            41 => 
            array (
                'id_reservation' => 42,
                'created_at' => '2023-07-20 10:15:49',
                'updated_at' => '2023-07-20 10:15:49',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-02',
                'customer_name' => 'NURSYAFRIYANI SIAK RIAU',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 400000,
                'notes' => NULL,
            ),
            42 => 
            array (
                'id_reservation' => 43,
                'created_at' => '2023-07-20 10:16:27',
                'updated_at' => '2023-07-20 10:16:27',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-02',
                'customer_name' => 'ARIS BUDIMAN',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 700000,
                'notes' => NULL,
            ),
            43 => 
            array (
                'id_reservation' => 44,
                'created_at' => '2023-07-20 10:16:58',
                'updated_at' => '2023-07-20 10:16:58',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-02',
                'customer_name' => 'BUK EVI',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 1000000,
                'notes' => NULL,
            ),
            44 => 
            array (
                'id_reservation' => 45,
                'created_at' => '2023-07-20 10:17:17',
                'updated_at' => '2023-07-20 10:17:17',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-02',
                'customer_name' => 'INSANI RAHESTI',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 1400000,
                'notes' => NULL,
            ),
            45 => 
            array (
                'id_reservation' => 46,
                'created_at' => '2023-07-20 10:17:50',
                'updated_at' => '2023-07-20 10:17:50',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-02',
                'customer_name' => 'RANI',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 950000,
                'notes' => NULL,
            ),
            46 => 
            array (
                'id_reservation' => 47,
                'created_at' => '2023-07-20 10:18:10',
                'updated_at' => '2023-07-20 10:18:10',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-02',
                'customer_name' => 'KAK RAHMI',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 850000,
                'notes' => NULL,
            ),
            47 => 
            array (
                'id_reservation' => 48,
                'created_at' => '2023-07-20 10:18:35',
                'updated_at' => '2023-07-20 10:18:35',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-02',
                'customer_name' => 'PAK YANDI',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 0,
                'notes' => NULL,
            ),
            48 => 
            array (
                'id_reservation' => 49,
                'created_at' => '2023-07-20 10:19:02',
                'updated_at' => '2023-07-20 10:19:02',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-02',
            'customer_name' => 'ISFARITA (PAK JHON MYHENDRI)',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 800000,
                'notes' => NULL,
            ),
            49 => 
            array (
                'id_reservation' => 50,
                'created_at' => '2023-07-20 10:19:20',
                'updated_at' => '2023-07-20 10:19:20',
                'deleted_at' => NULL,
                'year' => 2023,
                'month' => 7,
                'checkin_date' => '2023-07-02',
                'customer_name' => 'FITRIANI SYINTHIA',
                'customer_phone' => NULL,
                'total_guest' => NULL,
                'fix_price' => NULL,
                'down_payment' => 600000,
                'notes' => NULL,
            ),
        ));
        
        
    }
}