<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TrxDataFileTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('trx_data_file')->delete();
        
        \DB::table('trx_data_file')->insert(array (
            0 => 
            array (
                'id_data_file' => 1,
                'created_at' => '2023-09-05 11:29:08',
                'updated_at' => '2023-09-06 10:09:46',
                'deleted_at' => NULL,
                'created_by' => 'yudapramana',
                'updated_by' => '',
                'id_data_instansi' => 1,
                'id_data_kategori' => 11,
                'id_data_klasifikasi' => 2,
                'id_data_sub_klasifikasi' => 8,
                'nama_file' => 'Renstra Kemenag Kab. Pesisir Selatan Tahun 2020 - 2024',
                'ext' => 'pdf',
                'url_file' => 'https://ppid.kemenagpessel.com/storage/1/Renstra-Kemenag-Kab.-Pesisir-Selatan-Tahun-2020---2024.pdf',
                'tags' => NULL,
                'keterangan' => 'Rencana Strategis Kementerian Agama Kabupaten Pesisir Selatan Tahun 2020 - 2024',
                'hits' => 8,
                'download' => 0,
                'tahun' => 2020,
                'tempat' => 'Painan',
                'penanggung_jawab' => 'Kepala',
                'akses' => 'private',
                'status' => 'publish',
                'bentuk' => 'online',
            ),
            1 => 
            array (
                'id_data_file' => 2,
                'created_at' => '2023-09-05 11:32:19',
                'updated_at' => '2023-09-06 10:39:46',
                'deleted_at' => NULL,
                'created_by' => 'yudapramana',
                'updated_by' => '',
                'id_data_instansi' => 1,
                'id_data_kategori' => 2,
                'id_data_klasifikasi' => 4,
                'id_data_sub_klasifikasi' => 3,
                'nama_file' => 'LHKASN Kepala Kemenag Kab. Pesisir Selatan',
                'ext' => 'pdf',
                'url_file' => 'https://ppid.kemenagpessel.com/storage/2/LHKASN-Kepala-Kemenag-Kab.-Pesisir-Selatan.pdf',
                'tags' => NULL,
                'keterangan' => 'Laporan Harta Kekayaan ASN Kepala Kantor Kementerian Agama Kab. Pesisir Selatan Tahun 2022',
                'hits' => 4,
                'download' => 0,
                'tahun' => 2022,
                'tempat' => 'Painan',
                'penanggung_jawab' => 'Kepala',
                'akses' => 'private',
                'status' => 'publish',
                'bentuk' => 'online',
            ),
            2 => 
            array (
                'id_data_file' => 3,
                'created_at' => '2023-09-05 11:35:01',
                'updated_at' => '2023-09-05 12:07:32',
                'deleted_at' => NULL,
                'created_by' => 'yudapramana',
                'updated_by' => '',
                'id_data_instansi' => 1,
                'id_data_kategori' => 11,
                'id_data_klasifikasi' => 2,
                'id_data_sub_klasifikasi' => 8,
                'nama_file' => 'Rencana Kerja Kemenag Kab. Pesisir Selatan Tahun 2022',
                'ext' => 'pdf',
                'url_file' => 'https://ppid.kemenagpessel.com/storage/3/Rencana-Kerja-Kemenag-Kab.-Pesisir-Selatan-Tahun-2022.pdf',
                'tags' => NULL,
                'keterangan' => 'Rencana Kerja Kemenag Kab. Pesisir Selatan Tahun 2022',
                'hits' => 2,
                'download' => 0,
                'tahun' => 2022,
                'tempat' => 'Painan',
                'penanggung_jawab' => 'Kepala',
                'akses' => 'private',
                'status' => 'publish',
                'bentuk' => 'online',
            ),
            3 => 
            array (
                'id_data_file' => 4,
                'created_at' => '2023-09-05 11:40:39',
                'updated_at' => '2023-09-06 10:35:39',
                'deleted_at' => NULL,
                'created_by' => 'yudapramana',
                'updated_by' => '',
                'id_data_instansi' => 1,
                'id_data_kategori' => 2,
                'id_data_klasifikasi' => 2,
                'id_data_sub_klasifikasi' => 9,
                'nama_file' => 'Perjanjian Kerja Sama dengan SLB Negeri 1 Painan',
                'ext' => 'pdf',
                'url_file' => 'https://ppid.kemenagpessel.com/storage/4/Perjanjian-Kerja-Sama-dengan-SLB-Negeri-1-Painan.pdf',
                'tags' => NULL,
                'keterangan' => 'Perjanjian Kerja Sama dengan SLB Negeri 1 Painan',
                'hits' => 7,
                'download' => 0,
                'tahun' => 2023,
                'tempat' => 'Painan',
                'penanggung_jawab' => 'Kepala',
                'akses' => 'public',
                'status' => 'publish',
                'bentuk' => 'cetak',
            ),
            4 => 
            array (
                'id_data_file' => 5,
                'created_at' => '2023-09-05 11:49:30',
                'updated_at' => '2023-09-05 13:45:59',
                'deleted_at' => NULL,
                'created_by' => 'yudapramana',
                'updated_by' => '',
                'id_data_instansi' => 1,
                'id_data_kategori' => 2,
                'id_data_klasifikasi' => 2,
                'id_data_sub_klasifikasi' => 1,
                'nama_file' => 'Standar Pelayanan dan SOP Kelompok Ramah Rentan Inklusif Tahun 2023',
                'ext' => 'pdf',
                'url_file' => 'https://ppid.kemenagpessel.com/storage/5/Standar-Pelayanan-dan-SOP-Kelompok-Ramah-Rentan-Inklusif-Tahun-2023.pdf',
                'tags' => NULL,
                'keterangan' => 'Standar Pelayanan dan SOP Kelompok Ramah Rentan Inklusif Tahun 2023',
                'hits' => 4,
                'download' => 1,
                'tahun' => 2023,
                'tempat' => 'Painan',
                'penanggung_jawab' => 'Kepala',
                'akses' => 'public',
                'status' => 'publish',
                'bentuk' => 'online',
            ),
            5 => 
            array (
                'id_data_file' => 6,
                'created_at' => '2023-09-05 11:51:55',
                'updated_at' => '2023-09-05 12:28:06',
                'deleted_at' => NULL,
                'created_by' => 'yudapramana',
                'updated_by' => '',
                'id_data_instansi' => 1,
                'id_data_kategori' => 2,
                'id_data_klasifikasi' => 1,
                'id_data_sub_klasifikasi' => 2,
                'nama_file' => 'Laporan Kinerja Kakankemenag Kab. Pesisir Selatan Tahun 2022',
                'ext' => 'pdf',
                'url_file' => 'https://ppid.kemenagpessel.com/storage/6/Laporan-Kinerja-Kakankemenag-Kab.-Pesisir-Selatan-Tahun-2022.pdf',
                'tags' => NULL,
                'keterangan' => 'Laporan Kinerja Kepala Kantor Kementerian Agama Kabupaten Pesisir Selatan Tahun 2022',
                'hits' => 0,
                'download' => 0,
                'tahun' => 2022,
                'tempat' => 'Painan',
                'penanggung_jawab' => 'Kepala',
                'akses' => 'private',
                'status' => 'publish',
                'bentuk' => 'online',
            ),
            6 => 
            array (
                'id_data_file' => 7,
                'created_at' => '2023-09-05 12:36:25',
                'updated_at' => '2023-09-05 12:36:37',
                'deleted_at' => NULL,
                'created_by' => 'yudapramana',
                'updated_by' => '',
                'id_data_instansi' => 1,
                'id_data_kategori' => 1,
                'id_data_klasifikasi' => 3,
                'id_data_sub_klasifikasi' => 11,
                'nama_file' => '7 Tips Keamanan Internet',
                'ext' => 'pdf',
                'url_file' => 'https://ppid.kemenagpessel.com/storage/7/7-Tips-Keamanan-Internet.pdf',
                'tags' => NULL,
                'keterangan' => '7 Tips Keamanan Internet',
                'hits' => 0,
                'download' => 0,
                'tahun' => 2022,
                'tempat' => 'Painan',
                'penanggung_jawab' => 'Kepala',
                'akses' => 'public',
                'status' => 'publish',
                'bentuk' => 'online',
            ),
            7 => 
            array (
                'id_data_file' => 8,
                'created_at' => '2023-09-05 14:40:29',
                'updated_at' => '2023-09-05 14:40:29',
                'deleted_at' => NULL,
                'created_by' => 'yudapramana',
                'updated_by' => '',
                'id_data_instansi' => 3,
                'id_data_kategori' => 2,
                'id_data_klasifikasi' => 1,
                'id_data_sub_klasifikasi' => 3,
                'nama_file' => 'Laporan Keuangan Semester I Satker Bimas Islam Kankemenag Kab. Pessel',
                'ext' => 'pdf',
                'url_file' => 'https://ppid.kemenagpessel.com/storage/8/Laporan-Keuangan-Semester-I-Satker-Bimas-Islam-Kankemenag-Kab.-Pessel.pdf',
                'tags' => NULL,
            'keterangan' => 'Laporan Keuangan Semester I 299628 (Satker Bimas Islam Kankemenag Kab. Pessel)',
                'hits' => 0,
                'download' => 0,
                'tahun' => 2022,
                'tempat' => 'Painan',
                'penanggung_jawab' => 'Kepala',
                'akses' => 'private',
                'status' => 'draft',
                'bentuk' => 'online',
            ),
            8 => 
            array (
                'id_data_file' => 9,
                'created_at' => '2023-09-05 14:43:55',
                'updated_at' => '2023-09-05 14:43:55',
                'deleted_at' => NULL,
                'created_by' => 'yudapramana',
                'updated_by' => '',
                'id_data_instansi' => 3,
                'id_data_kategori' => 2,
                'id_data_klasifikasi' => 1,
                'id_data_sub_klasifikasi' => 3,
                'nama_file' => 'Laporan Keuangan Semester I 299630 Direktorat Jenderal PHU',
                'ext' => 'pdf',
                'url_file' => 'https://ppid.kemenagpessel.com/storage/9/Laporan-Keuangan-Semester-I-299630-Direktorat-Jenderal-PHU.pdf',
                'tags' => NULL,
                'keterangan' => 'Laporan Keuangan Semester I 299630 Direktorat Jenderal PHU',
                'hits' => 0,
                'download' => 0,
                'tahun' => 2023,
                'tempat' => 'Painan',
                'penanggung_jawab' => 'Kepala',
                'akses' => 'public',
                'status' => 'draft',
                'bentuk' => 'cetak',
            ),
            9 => 
            array (
                'id_data_file' => 10,
                'created_at' => '2023-09-05 15:08:08',
                'updated_at' => '2023-09-06 07:28:55',
                'deleted_at' => NULL,
                'created_by' => 'yudapramana',
                'updated_by' => '',
                'id_data_instansi' => 1,
                'id_data_kategori' => 2,
                'id_data_klasifikasi' => 1,
                'id_data_sub_klasifikasi' => 1,
                'nama_file' => 'Laporan Pelayanan PTSP Kemenag Pessel Tahun 2022',
                'ext' => 'pdf',
                'url_file' => 'https://ppid.kemenagpessel.com/storage/10/Laporan-Pelayanan-PTSP-Kemenag-Pessel-Tahun-2022.pdf',
                'tags' => NULL,
                'keterangan' => 'Laporan Pelayanan PTSP Kementerian Agama Kabupaten Pesisir Selatan Tahun 2022',
                'hits' => 4,
                'download' => 0,
                'tahun' => 2022,
                'tempat' => 'Painan',
                'penanggung_jawab' => 'Kepala',
                'akses' => 'public',
                'status' => 'draft',
                'bentuk' => 'online',
            ),
        ));
        
        
    }
}